### ISSUE TITLE
just stopt working without any log

### ISSUE THREAD

**Issue by tobyknobi** [tijsverkoyen/HomeAssistant-FusionSolar#100]
Yesterday the integration just didnt provide any data. Or maybe its not the integration but something at Huawei.
Is this something others have issues with??
No updates or any other changes.
Just in the middle of the day no data anymore

**Comment by tijsverkoyen** [comment]
I think the best way forward will be to contact Huawei Fusion Solar support.

**Comment by tobyknobi** [comment]
Oké. Will do it.

Thanks.

Op wo 12 jul. 2023 14:11 schreef Tijs Verkoyen ***@***.***>:

**Comment by valentinfrlch** [comment]
Check if "Deadline" is a date in the future: 
<img width="845" alt="image" src="https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/85313672/527e8557-073a-41da-817a-070f9cf9eb4f">
System→Company Management→Northbound Management→Edit

**Comment by tijsverkoyen** [comment]
@tobyknobi can you check if this resolves your issue?

**Comment by tobyknobi** [comment]
Oké I am waiting on my installer, because I can't go into the Northbound system.
As soon as I know I will let everyone know.

**Comment by tobyknobi** [comment]
Oké that was the problem. You can close the issue

**Comment by tobyknobi** [comment]
Thans for you fast support

**Comment by tijsverkoyen** [comment]
No need to thank me, @valentinfrlch deserves the credits ;-)
