### ISSUE TITLE
v2.6.0, HA 23.07.1

### ISSUE THREAD

**Issue by QaDoPL** [tijsverkoyen/HomeAssistant-FusionSolar#101]
At _active_power there is no possibility change measuring unit from kW to W.
After change is still stuck at kW.

**Comment by tijsverkoyen** [comment]
Can you be a bit more specific, because normally they are reported as the unit the API provides them.
Which entity specifically is faulty? For which device?

**Comment by tijsverkoyen** [comment]
@QaDoPL can you check the comment above?

**Comment by tijsverkoyen** [comment]
@QaDoPL I will close this issue as there is no feedback.
