### ISSUE TITLE
FusionCharge charger integration

### ISSUE THREAD

**Issue by P-Stenbumling** [tijsverkoyen/HomeAssistant-FusionSolar#105]
Is the huawei charger available?

**Comment by tijsverkoyen** [comment]
What do you mean with that?
Did you try? Do you have some more info?
Which device is this exactly?

**Comment by P-Stenbumling** [comment]
Hi!

Sorry for the lack of information
Software Version: FusionCharge V100R022C10SPC070 
AC Charger Model
SCharger-22KT-S0 
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/39261692/65ed8385-b6f9-4854-985c-16fef036927b)

**Comment by tijsverkoyen** [comment]
I don't think so. 
Is there anything exposed in the FusionSolar App on your phone? Or in the Kiosk?

**Comment by tijsverkoyen** [comment]
I don't think it is supported.
Do you see anything in the FusionSolar app on your phone or in the kiosk?
Feel free to share your credentials with me (`fusionsolar-ha [at] Verkoyen [dot] eu`), and I can take a look

**Comment by P-Stenbumling** [comment]
Yes,

![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/39261692/5c0d6efb-bc3a-44b9-b17b-5dac2a39e533)
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/39261692/17d3deca-e1a3-49c2-9b4f-ccd3fea9a175)
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/39261692/f422cba3-50b3-4a20-9eb1-c4370716225f)

**Comment by tijsverkoyen** [comment]
Are you willing to share your credentials? So I can check if the data is available in the API?
But don't get your hope up, as I don't see anything in the documentation about FusionCharge

**Comment by karliwalti** [comment]
May I please reopen the issue? 
According to this post, the charger can be started using the API https://forum.huawei.com/enterprise/en/api-capabillities-scharger-22kt-s0/thread/695710147218915328-667213868771979264

**Comment by karliwalti** [comment]
To facilitate the dev, I collect the existing cmd posted in forums (unfortunately I could not find the API documentation for it yet):

```

GET https://eu5.fusionsolar.huawei.com/thirdData/getChargerList
Authorization: Bearer YOUR_ACCESS_TOKEN
```

```
GET https://eu5.fusionsolar.huawei.com/thirdData/getChargerRealKpi
Authorization: Bearer YOUR_ACCESS_TOKEN
chargerCode=YOUR_CHARGER_CODE
```

```
POST /api/v2/chargers/1234567890/start_charging

{
  "start_time": "2023-03-08T12:00:00Z",
  "duration": 60
}
```

**Comment by tijsverkoyen** [comment]
You may. 

At this point the integration is only reading data, not pushing data to the API. And to be honest I don't am very keen on adding this.

Can you tell we which device you exactly have? And are you willing to share your credentials? As I don't own a charger.

**Comment by mega-alexraab** [comment]
Hello,
@tijsverkoyen 
I have the complet Huawei Sun Power Station and the Chager SCharger-22KT-S0 and full access to the system.
What credentials to you need?
I'm very interested to see more online data's from the charger. 

> You may.
> 
> At this point the integration is only reading data, not pushing data to the API. And to be honest I don't am very keen on adding this.
> 
> Can you tell we which device you exactly have? And are you willing to share your credentials? As I don't own a charger.

**Comment by karliwalti** [comment]
Sorry for my delay, I was waiting to get the API access, but still waiting...
Once I have, would be happy to share access for a while. 
Plant Setuo: SCharger-22KT-S0, SUN200-8KTL-M1, 5kW battery

**Comment by lucabacchipg** [comment]
Hello, i'm going crazy because i shoud want integrate fusioncharge s22 into my Home Assistant Dashboard.
I have a full control of my installation (i'm reseller too).
Can you help me ? 
Do you need a documentation of Huawei
[SmartPVMS 24.2.0 Northbound API Reference.pdf](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/files/15312165/SmartPVMS.24.2.0.Northbound.API.Reference.pdf)
 API ?
I should want to control Charging Status, Actual Power, KW loaded, Session Time, and some other issue.

**Comment by karliwalti** [comment]
I am selling my SCharger. That thing can´t even do phase switching when configured in 11kW.

**Comment by tijsverkoyen** [comment]
At this point I will not invest any time to add support for FusionCharge charger

**Comment by lucabacchipg** [comment]
> At this point I will not invest any time to add support for FusionCharge charger

why not ?

**Comment by tijsverkoyen** [comment]
> > At this point I will not invest any time to add support for FusionCharge charger
> 
> why not ?

Don't take this personally. But there are a multiple reasons. 
I don't want to be ungrateful or impolite but:

* Time, my days only have 24 hours. I need to prioritise. This project is not what pays the bills.
* Work/Life. Related to the first one, but my wife also deserves time.
* I don't own a charger. A very selfish reason, I know. At this point I don't have a charger. If I need one I will look to different brands, Huawei may be an option. At that point there will be a personal need 

Feel free to create a Pull Request, I will be happy to review.

**Comment by karliwalti** [comment]
> > I am selling my SCharger. That thing can´t even do phase switching when configured in 11kW.
> 
> Which means ?

That I have no longer the SCharger installed and won´t be able to provide access for development. 
I also think it is not a very good product and do recommend buying another charger that provides access to core functions via local API calls which are openly published. An example how it could be done: https://github.com/goecharger/go-eCharger-API-v2
