### ISSUE TITLE
Cannot change the Unit of Measurement 

### ISSUE THREAD

**Issue by LPirro** [tijsverkoyen/HomeAssistant-FusionSolar#110]
Hello, I want to report a bug:

My Battery default measurement unit is Watt, and I want to use kW instead. But when I change the Unit of Measurement in settings (see screenshot) nothing changes and stays on W. The entity is `battery_1_charge_discharge_power` 

**Screenshot**
![Screenshot 2023-09-08 at 10 05 55](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/3328096/6b79f2f7-ce3a-41d6-8dea-9f7b5d6d2302)

**Comment by tijsverkoyen** [comment]
@LPirro could you apply the changes in https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/111 and let me know if it works. 
I don't have a battery in my setup so I can't test it for all devices.

Be aware that this could cause backwards compatibility. As some of the entities have been changed.

**Comment by LPirro** [comment]
Thanks for the reply! ❤️

I will create another home assistant instance for testing and I will let you know, I don't want to break my current setup.

Happy to help testing this! 🙏🏻

**Comment by LPirro** [comment]
> @LPirro have you tried with these changes?

@tijsverkoyen I just tested the changes, and they are working!

Thanks!

**Comment by tijsverkoyen** [comment]
Thx. I have created a new release: https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/releases/tag/v3.0.0
