### ISSUE TITLE
Kiosk stop's displaying data

### ISSUE THREAD

**Issue by smalarz** [tijsverkoyen/HomeAssistant-FusionSolar#113]
FusionSolar was working flawlessly for me for about a year. After the recent HA updates to the latest versions, I don't see any data in the entity at all. Are you also experiencing this problem?

![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/64301502/333467be-7c64-4ad5-8f5e-a984bed469c9)

**Comment by tijsverkoyen** [comment]
I don't experience this issue. I still see the data getting updated.
Which version of Home Assistant are you using? Which version of the integration? Is there anything in the logs?

**Comment by Jeygi** [comment]
I got the same issue. I try my Kiosk URL and it is not working anymore. The kiosk was created 1 year ago. Perhaps there is a kind of expiration for the kiosk.
Is there a way to update the URL in the integration?

**Comment by tijsverkoyen** [comment]
@smalarz Are you also using Kiosk mode?
Is the kiosk url still working?

@Jeygi you should be able to find the original url in `.storage/core.config_entries`

**Comment by smalarz** [comment]
actually the kiosk doesn't work

**Comment by smalarz** [comment]
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/64301502/166fff6b-547b-4e8c-94e6-8f846eb0fad5)

**Comment by tijsverkoyen** [comment]
Yeah, you will need to replace the kiosk url.
Or you can remove the integration and configure it again. I don't know for sure: but probably you will lose history.

**Comment by smalarz** [comment]
what about OpenAPI?

**Comment by smalarz** [comment]
The new kiosk actually solves the problem. Thanks for the help.
