### ISSUE TITLE
Missing sensors in kiosk-mode

### ISSUE THREAD

**Issue by rallyeaon** [tijsverkoyen/HomeAssistant-FusionSolar#115]
Hello!
I have the FusionSolar integration which works for 5 sensors only (see screenshot below).
![Bildschirmfoto 2023-11-12 um 13 29 04](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/95368092/3fbda720-7fd7-45a6-a547-afde59286dc5)

For the Energy-Dashboard I can use `sensor.xxx_total_current_day_energy` which is available to me. However, the remaining sensors outlined in the documentation are unavailable (i.e. Grid consumption `sensor.xxx_reverse_active_energy` and Return to grid `sensor.xxx_active_energy_forward_active_energy`). Not sure what I'm doing wrong.

Please note: I have no battery in my installation

Thank you - Rallye

**Comment by Guenni75** [comment]
Kiosk mode doesn't support all sensors.

![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/14917841/84622cbb-fde2-4a8f-806e-7089361e5b34)

That's all you can get.

For more you need an API-Key.

**Comment by Guenni75** [comment]
Hi.
No, you can not get these over Kiosk Mode.
Its with an Api Key.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Mo., 13. Nov. 2023 um 09:19 Uhr schrieb Tijs Verkoyen <
***@***.***>:

**Comment by Guenni75** [comment]
This is all i can get over Kiosk Mode:
[image: image.png]

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Mo., 13. Nov. 2023 um 12:38 Uhr schrieb Jörg ***@***.***>:

**Comment by tijsverkoyen** [comment]
@Guenni75 I don't understand your reply. As in the image in the issue it is shown that Kiosk is used.

**Comment by Guenni75** [comment]
Yes, but you can't get the battety with Kiosk Mode and the data of the Kiosk Mode has 30 Minutes delay.
This is a pictute from the FusionSolar Kiosk Settings.
For Home Assistant, i use the Northbound Apikey.

**Comment by tijsverkoyen** [comment]
![Missing_sensors_in_kiosk-mode_·_Issue__115_·_tijsverkoyen_HomeAssistant-FusionSolar](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/250042/8b259303-54be-4412-8ec5-8b82075eadbf)

**Comment by Guenni75** [comment]
Right!
Thats why there are only 5 Sensors!!

Issue can be closed, because there is nothing missing.
