### ISSUE TITLE
Meter and Battery unknown

### ISSUE THREAD

**Issue by Guenni75** [tijsverkoyen/HomeAssistant-FusionSolar#116]
I have problems with the battery and meter sensors:

Battery:
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/14917841/143dace6-b832-4d1f-85cc-6927faeb8dcf)

Meter:
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/14917841/81604af5-6eaf-466b-a75e-711eb3f493ec)

The other Sensors work.

At the FusionSolar Website, ALL Sensors work as well.

Any Idea??

**Comment by tijsverkoyen** [comment]
Do you use Kiosk mode? If so: can you check if the kiosk URL has not changed?

**Comment by Guenni75** [comment]
Hi.
I use an API-Key.
You can not get the battery with Kiosk Mode.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Mo., 13. Nov. 2023 um 09:18 Uhr schrieb Tijs Verkoyen <
***@***.***>:

**Comment by Guenni75** [comment]
There was an issue with the Apikey.
The integration works perfect.
