### ISSUE TITLE
Entity not available (Power Sensor) but displayed in Entities

### ISSUE THREAD

**Issue by impish1234** [tijsverkoyen/HomeAssistant-FusionSolar#118]
Hello,

Yesterday i setup a new HA system and install your great FusionSolar plugin.
Everything works fine but in grid settings i get following message

statistics_not_defined
sensor.meter_1_active_energy_forward_active_energy
sensor.meter_1_reverse_active_energy

Entity not available
The status of these configured entities is currently unavailable:
sensor.meter_1_active_energy_forward_active_energy (unknown)
sensor.meter_1_reverse_active_energy (unknown)

If i check my entities - both will be displayed - also during editing intellisense suggest it.

thank markus

**Comment by tijsverkoyen** [comment]
I don't understand your issue. Could you clarify with some screenshots?
