### ISSUE TITLE
Not showing entities that I was expecting.

### ISSUE THREAD

**Issue by 01010100cc** [tijsverkoyen/HomeAssistant-FusionSolar#119]
Had a new system installed yesterday and just looking to see if I can get this working. 
First of all, thanks for putting this together, will be really useful!

I did the kiosk mode for now but I don't seem to have things like battery entities or some of the ones mentioned in the documentation. Am I missing something? Is kiosk limited in frequency and entities? 

Here are the entities that I can see. 

![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/20030089/c68a4a4f-c8c5-4415-a4d7-13062fa25c58)

**Comment by tijsverkoyen** [comment]
I don't really know what you expect? Kiosk-mode does not expose that much data, so there are limited entities.

**Comment by 01010100cc** [comment]
Sorry, I was not sure if the kiosk mode had more info that was not shown on
the url. Apologies, this can be closed :)
