### ISSUE TITLE
No stations found in OpenAPI

### ISSUE THREAD

**Issue by tacuszka** [tijsverkoyen/HomeAssistant-FusionSolar#12]
I successfully added FusionSolar integration in HAACS and Settings > Integrations. Selected OpenAPI, typed in username and password (got those from Huawei support while creating OpenAPI access). Authorization is also successful, but I don't see services or entities being made. 

```
Error log:
homeassistant.exceptions.IntegrationError: No stations found in OpenAPI
```

I tried sending API requests using Postman. Authorization works; I receive XSRF-TOKEN. When I use the token to getStationList, I'm getting only:

```
{
    "data": [],
    "failCode": 0,
    "message": null,
    "params": {
        "currentTime": 1668952257900
    },
    "success": true
}
```

The data parameter is empty - I'm not getting the stationCode back. 

Am I doing something wrong, or is this for Huawei to fix?

**Comment by tijsverkoyen** [comment]
You should contact Huawei to link your plant to your OpenAPI account.
