### ISSUE TITLE
Open API issue

### ISSUE THREAD

**Issue by kikect** [tijsverkoyen/HomeAssistant-FusionSolar#122]
Hi, I was facing a not refresh issue with the inverter data via OpenAPI connection. If I reboot HA the data is refresh for two hours and then it freezes again. any update on this? Thans so much for your support

**Comment by danielsjf** [comment]
Same issue here. I only have the integration since a few days, but I don't succeeds in getting the readouts for a longer period. It works initially, but then all sensors become unavailable. I have to add another hub to make it work again.

**Comment by tijsverkoyen** [comment]
Can you enable debug logging and check logs for errors?

**Comment by danielsjf** [comment]
I was looking at the wrong sensors apparently. The Inverter statistics do update and keep on updating. However, the lifetime statistics under the account device only update the first time and afterwards never again. As a work around I've taken the Inverter statistics.

Thanks for the suggestions and creating this awesome integration!

**Comment by kikect** [comment]
Seems it´s working fine now. The data is refreshed every 5 minutes as usual. Maybe a Huawei API issue. Thanks for your support!
