### ISSUE TITLE
No data in OpenAPI mode since January 1st

### ISSUE THREAD

**Issue by Brandyellow** [tijsverkoyen/HomeAssistant-FusionSolar#126]
I stopped receiving data on my "Total current day energy" entity 14:00 CET on the 1st of January.
Currently when opening the entity I get the following error message:
"This entity is no longer being provided by the fusion_solar integration. If the entity is no longer in use, delete it in settings."
This is the same for all entities provided by my Fusion Solar OpenAPI integration.

I have my integration configured in core.config_entries:

![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/112823903/7e6369d2-9b97-45ab-aa71-8087a8db3c82)

I am hesitant to remove the integration and set it up again since I don't wanna lose the old statistics.

When trying to add new hub I get the error message "Could not authenticate with the provided credentials.":

![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/112823903/ea031d5e-fe12-4aff-aeed-80a206cba733)

**Comment by ugfus1630** [comment]
Same problem here, all entities are unavailable since 2nd of January, 19:18 gmt+1

![Screenshot_2024-01-04-22-02-37-582_io homeassistant companion android](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/98426316/e23b6262-ccbc-4725-b97c-284ff7b0e00c)

**Comment by tijsverkoyen** [comment]
Are other entities still updating?
Are you willing to share your credentials with me? (‘FusionSolar-ha at verkoyen dot eu’)

**Comment by mrcsrplln** [comment]
I am experiencing the same issue, though in my installation it started randomly on the 4th of January:

![Screenshot_20240105-090237](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/73736866/80481e77-39de-482c-a50a-3bb84a1e5d32)

Fusion Solar app is working fine on the other hand:

![Screenshot_20240105-090425](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/73736866/b3a75523-41e2-4beb-8b3b-f16742707b24)

**Comment by tijsverkoyen** [comment]
@Brandyellow 

> When trying to add new hub I get the error message "Could not authenticate with the provided credentials.":

This means the credentials are not valid. Can you check with your installer if they have disabled the credentials?

**Comment by tijsverkoyen** [comment]
You can verify your credentials by doing a curl call like below.

````
curl --location 'https://eu5.fusionsolar.huawei.com/thirdData/login' \
--header 'Content-Type: application/json' \
--data '{
    "userName": "XXX",
    "systemCode": "YYY"
}'
````

Check if you need to alter the base hostname `https://eu5.fusionsolar.huawei.com`. And replace `XXX` with your username and `YYY` with your password.

The response should look like:

````json
{
  "data": null,
  "success": true,
  "failCode": 0, 
  "params": {},
  "message": null
}
````

**Comment by ugfus1630** [comment]
> Are other entities still updating? Are you willing to share your credentials with me? (‘FusionSolar-ha at verkoyen dot eu’)

All entites are in the same state, not available.
![kép](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/98426316/2a20ff45-37b4-4d5e-aa21-76c9908b6f54)

Of course I can share my credentials with you, but I do not want to write here, can I send a private message somehow?

**Comment by tijsverkoyen** [comment]
> I used Postman to send a login request to Fusionsolar and got the response "northbound system has expired."
> Should I contact my installer to check if my account is still active? Are you helped by my credentials?

Yes. The error means your credentials are not valid anymore.

**Comment by tijsverkoyen** [comment]
@ugfus1630 
 
> Of course I can share my credentials with you, but I do not want to write here, can I send a private message somehow?

Feel free to mail the, as mentioned above, to: ‘fusionSolar-ha [at] verkoyen [dot] eu’
Or you can check yourself if they are still valid: [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar#how-can-i-verify-my-northbound-api--openapi-credentials)

**Comment by Brandyellow** [comment]
> @Brandyellow
> 
> > I used Postman to send a login request to Fusionsolar and got the response "northbound system has expired."
> > Should I contact my installer to check if my account is still active? Are you helped by my credentials?
> 
> Yes. The error means your credentials are not valid anymore.

I've added a ticket to my installer (1komma5) and we'll see how they respond.

**Comment by ugfus1630** [comment]
I have sent my credentials to you.

**Comment by tijsverkoyen** [comment]
@ugfus1630 You have the same issue as @Brandyellow. You will need to contact your installer to check your credentials.

```
Fusion Solar API debug
======================

 * Login: XXX
 * Password: YYY

→ Testing /login: ❌
                                                                                                                      
 [ERROR] API Error (20003): northbound system has expired.                                                              
```

**Comment by ugfus1630** [comment]
oh, I am going to contact with my installer, thank you very much!

**Comment by Brandyellow** [comment]
I guess this issue can be closed now.

Thank you again, @tijsverkoyen!

**Comment by JohnMcLear** [comment]
I am the installer for me..

At first I got 
```
{"data":null,"success":false,"failCode":20003,"params":{"currentTime":1735912080655},"message":"northbound system has expired."}
```
Then I went into the UI and set the expiry to a date in the future

![image](https://github.com/user-attachments/assets/7a1c38aa-16f2-4f36-b1f5-8a0d594eb038)

This resulted in

```
{"data":null,"success":false,"failCode":20400,"params":{"currentTime":1735912091688},"message":"user.login.user_or_value_invalid"}
```

I also tried a deadline that isn't as far in the future IE within next 12 months, this failed..

**Comment by Brandyellow** [comment]
Where did you change the expiry date, @JohnMcLear?

Can't remember any GUI for the installer account, just using the API...
