### ISSUE TITLE
Wrong state_class of 'HV2110048848 - Yield Today' entity

### ISSUE THREAD

**Issue by ltorzynski** [tijsverkoyen/HomeAssistant-FusionSolar#13]
Should be of type 'total_increasing', but is of type 'measurement' 

 The energy dashboard is not accepting measurement for an energy entity - The state class for “energy” entities should be “total_increasing” (energy consumed since the last reset), “measurement” is suitable for “power” entities expressed in W

https://community.home-assistant.io/t/energy-dashboard-last-reset-missing/406733/2

**Comment by tijsverkoyen** [comment]
Fixed in https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/releases/tag/v2.1.0
