### ISSUE TITLE
Entities not Updating in Kiosk Mode

### ISSUE THREAD

**Issue by Julimos** [tijsverkoyen/HomeAssistant-FusionSolar#140]
**Describe the bug**
After an Update of the Fusionsolar App/Kiosk Website (?) entities are not Updated anymore

** Debug information **
Answer the questions below before submitting a new issue.

* Are you using Kiosk or Northbound / OpenAPI mode?
  * [x] Kiosk
  * [ ] Northbound OpenAPI
* If you are using Kiosk mode. Have you checked that the url is still valid? See [I am using the kiosk mode, but the data is not updating](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#i-am-using-the-kiosk-mode-but-the-data-is-not-updating)

Checked the URL, it is still working, also added a new Hub that does not work as well. 

* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. See [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#how-can-i-verify-my-northbound-api--openapi-credentials)
 

**To Reproduce**
1. Go to 'Fusion Solar Entities'

**Expected behavior**
Data should be updating

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Home Assistant Core 2024.1.4]

**Additional context**

**Comment by srusinov** [comment]
I suppose this is the same issue as on my end: 

Unexpected error fetching FusionSolarKiosk data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fusion_solar/sensor.py", line 79, in async_update_kiosk_data
    data[f'{DOMAIN}-{kiosk.id}'] = await hass.async_add_executor_job(api.getRealTimeKpi, kiosk.id)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fusion_solar/fusion_solar/kiosk/kiosk_api.py", line 37, in getRealTimeKpi
    jsonData[ATTR_DATA] = json.loads(html.unescape(jsonData[ATTR_DATA]))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Maybe the protocol changed recently?

**Comment by psleutel** [comment]
After deleting the integration and adding it again everything worked again

**Comment by Julimos** [comment]
Works again since today

**Comment by magilla13** [comment]
This issue started to me today.
All the entities are unavailable. If I delete the app and reinstall it is working but loosing all the historical data...

**Comment by tijsverkoyen** [comment]
What happens if you just restart Home Assistant?

**Comment by Julimos** [comment]
For me, restarting did not help. 
But still works as reported yesterday.

**Comment by magilla13** [comment]
Restart itself didn't help, but somehow today started to work again properly...

**Comment by tijsverkoyen** [comment]
Ok, so it works for everyone again?
I'm going to close the issue. Feel free to reopen it if it is not resolved. Although I think it is more Huawei related then to this integration
