### ISSUE TITLE
Half of entities are unavailable 

### ISSUE THREAD

**Issue by JohnBenson00** [tijsverkoyen/HomeAssistant-FusionSolar#144]
![Screenshot_2024-01-29-10-04-48-163_io.homeassistant.companion.android.jpg](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/154667383/cb362065-f0db-42cf-ae52-d8ebe79a802c)

**Comment by eclyptox** [comment]
Same here. Last week there was a manteinance mode notified in the fusion solar app. Maybe something has changed.

**Comment by tijsverkoyen** [comment]
I would suggest to give it some time. As there are already many other issues that resolved themself after a while, or after a reboot of Home Assistant:

- https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/143
- https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/140
- App update made all entities unavailable  #139
- https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/125
- https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/123

**Comment by JohnBenson00** [comment]
So sorry about the missing details, i am using Northbound API, the problem was that i didnt have "real time data" enabled. thanks for the help

**Comment by eclyptox** [comment]
I restarted HA and now everything is working.
