### ISSUE TITLE
User/pass is output to log file.

### ISSUE THREAD

**Issue by JohnMcLear** [tijsverkoyen/HomeAssistant-FusionSolar#153]
```
2024-02-25 11:56:33.595 DEBUG (MainThread) [custom_components.fusion_solar.config_flow] async_step_openapi: {'host': 'https://eu5.fusionsolar.huawei.com', 'username': 'exampleusername', 'password': 'examplepassword'}
```

For security reasons you don't want to output user/passwords to log files.

**Comment by tijsverkoyen** [comment]
This is only logged in debug mode. Also: the password is stored in clear text in Home Assistant, as there is no way to encrypt this (as far as I know)

**Comment by tijsverkoyen** [comment]
If I check the links, there is no solution to redact content from the logs. Feel free to create a PR that removes https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/custom_components/fusion_solar/config_flow.py#L79

I never ask people to share their credentials on Github itself, and I also remove credentials if I see them being posted here.
