### ISSUE TITLE
Always disconnecting

### ISSUE THREAD

**Issue by JohnBenson00** [tijsverkoyen/HomeAssistant-FusionSolar#154]
**Describe the bug**
After the last update (like 5 days ago) fusion solar enteties are sometimes unavailible (they only work for 1 hour every 2 hours"

** Debug information **
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant?
Yes
* Are you using the latest version of this integration?
Yes
* Have you looked into the closed issues and did not find a similar issue.
Yes
* Are you using Kiosk or Northbound / OpenAPI mode?
Northbound
* If you are using Kiosk mode. Have you checked that the url is still valid? See [I am using the kiosk mode, but the data is not updating](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#i-am-using-the-kiosk-mode-but-the-data-is-not-updating)
* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. See [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#how-can-i-verify-my-northbound-api--openapi-credentials)
* Have you checked the logs for any info? 

**To Reproduce**

**Expected behavior**

**Screenshots**
 ![Screenshot_2024-03-02-10-34-14-158_io.homeassistant.companion.android-edit.jpg](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/154667383/67117a11-96d5-44ab-b014-de0e0cf07576)

![Screenshot_2024-03-02-10-34-26-412_io.homeassistant.companion.android-edit.jpg](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/154667383/6c598e8e-c3ff-4545-9e47-a75b9d7f082c)

**Comment by tijsverkoyen** [comment]
Is suspect you have a lot of devices? And you are running into Huawei rate limiting. Normally you will see this in the logs.

**Comment by tijsverkoyen** [comment]
@JohnBenson00 Any feedback?

**Comment by JohnBenson00** [comment]
> @JohnBenson00 Any feedback?

![Screenshot_2024-03-18-21-41-07-537_io.homeassistant.companion.android-edit.jpg](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/154667383/a5990406-d786-4e8e-946d-c56a7f5653db)

It works now. Sometimes it does that, where it disconnects for multiple times but lately it has been working fine, there was probably an outage on fusion's api side when i posted it
