### ISSUE TITLE
Energy dashboard showing wrong values

### ISSUE THREAD

**Issue by ward0** [tijsverkoyen/HomeAssistant-FusionSolar#157]
**Describe the bug**

** Debug information **
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant? Yes
* Are you using the latest version of this integration? Yes
* Have you looked into the closed issues and did not find a similar issue. Yes
* Are you using Kiosk or Northbound / OpenAPI mode? OpenAPI mode - credentials valid
* Have you checked the logs for any info? Yes, no info

**Expected behavior**

My grid usage is wrong, in fusion solar app i can see it is 0 at the moment, HA showing 2.8 kWh..
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/15545810/24fded21-18c9-426a-9b6b-21360d4e3b36)

Home is showing 3.1 kWh, but fusion app showing 0,33kW
I have no idea how HA is calculating that 3.1 kWh
Probably a combination of some sensors...

**Screenshots**
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/15545810/6703daca-542e-47a5-9e4d-aa5b0354c67e)
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/15545810/2f94da70-9e89-4850-893f-d50e4251e5e8)
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/15545810/82cd4198-7f85-4d1d-81e9-d7453e6ce6a1)

API delay in HA is 20 minutes? Can we go lower than this default value?

Thanks for your work.

**Comment by tijsverkoyen** [comment]
> Home is showing 3.1 kWh, but fusion app showing 0,33kW

Note that the Fusion Solar app can use a different schedule to update the data then this integration. So it is very realistic that values don't match up.


> I have no idea how HA is calculating that 3.1 kWh
> Probably a combination of some sensors...

To my knowledge, but I am not a core Home Assistant developer. The Energy dashboard uses the information from the sensor you provide. So you should be able to trace the datapoints, or at least recognise the values.

> API delay in HA is 20 minutes? Can we go lower than this default value?

No. Not without running into rate limiting.
You could disable some device to speed up the updating. See https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#disabling-devices--plants--stations

**Comment by ward0** [comment]
@tijsverkoyen Thx for the info, found out that my dashboard is showing my totals :) not the current values.
Seems logic in the end because of the delay.
