### ISSUE TITLE
Wrong  device_class?

### ISSUE THREAD

**Issue by moritzstones** [tijsverkoyen/HomeAssistant-FusionSolar#158]
I can not integrate all entities into the energy dashboard, even though the developer tool shows the values trasmitted via the Northbound API tool and updates them regularly. 

I believe this is due to a wrong `device_class`. The `device_class` reads `power`, but I thik it should be `energy`. Or am I totally lost here?

<img width="731" alt="image" src="https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/152225685/7ea4c36b-8f68-4ff5-84d1-b2b17cc7aa00">

Ref.: 
https://www.home-assistant.io/docs/energy/faq/#troubleshooting-missing-entities

**Comment by tijsverkoyen** [comment]
The energy dashboard needs "energy" entities. Not "power". The entity in your screenshot is the active power, not active energy.

See https://github.com/tijsverkoyen/HomeAssistant-FusionSolar?tab=readme-ov-file#integration-with-the-energy-dashboard on how to configure the Energy Dashboard.
