### ISSUE TITLE
Steps in cumulative quantities. (open api)

### ISSUE THREAD

**Issue by grinsted** [tijsverkoyen/HomeAssistant-FusionSolar#159]
**Describe the bug**
Weird steps in many cumulative properties such as total current year energy
![Screenshot_2024-04-05-08-34-52-512_io homeassistant companion android~2](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/2535390/af074842-9782-4663-a597-d72840ab5e68)
.
This affects many quantities and seem to happen daily at a consistent time of day. Maybe when battery is out of power.

** Debug information **
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant?
* yes
* Are you using the latest version of this integration?
* yes
* Have you looked into the closed issues and did not find a similar issue. Yes
* Are you using Kiosk or Northbound / OpenAPI mode?
Api

* Have you checked the logs for any info? 

2024-04-04 23:05:10.108 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.tofthojvej_8_total_current_year_energy from integration fusion_solar has state class (https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/2535390/de705ef6-850f-4f30-99af-4e53f8b1da01)
total_increasing, but its state is not strictly increasing. Triggered by state 670.939999999999 (712.5) with last_updated set to 2024-04-04T21:03:01.755868+00:00. Please create a bug report at https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues

**Comment by tijsverkoyen** [comment]
Yeah, this is a Huawei issue. I will not invest any time to fix this.
