### ISSUE TITLE
Error requesting FusionSolarKiosk data

### ISSUE THREAD

**Issue by Zkaning** [tijsverkoyen/HomeAssistant-FusionSolar#163]
**Describe the bug**
Error requesting FusionSolarKiosk data. Happens randomly.  Restored after random time.

** Debug information **
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant? Yes
* Are you using the latest version of this integration? Yes
* Have you looked into the closed issues and did not find a similar issue. Yes
* Are you using Kiosk or Northbound / OpenAPI mode? Yes
* If you are using Kiosk mode. Have you checked that the url is still valid? Yes
* If you are using Northbound / OpenAPI mode. Check if your credentials are still valid: Yes
* Have you checked the logs for any info? HTTPSConnectionPool(host='region02eu5.fusionsolar.huawei.com', port=443): Max retries exceeded with url: /rest/pvms/web/kiosk/v1/station-kiosk-file?kk=xxxxxxxxxxxxxxxxxx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff27554f50>: Failed to establish a new connection: [Errno -3] Try again'))

**Expected behavior**
Not loosing connection :)

**Comment by tijsverkoyen** [comment]
Yeah, this is a Huawei issue. I will not invest any time to fix this.
