### ISSUE TITLE
Some numerical sensors do not allow to be used completely in the statistics cards

### ISSUE THREAD

**Issue by jvcsw** [tijsverkoyen/HomeAssistant-FusionSolar#167]
**Describe the bug**
All numerical sensors do not allow to be used completely in the statistics cards. For exemple, these sensors:

![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/60681048-7c75-4576-8bea-c4eb36cdbbbb)

these sensors have the max, min, mean options disabled

![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/f4ea73c5-6627-4009-ba26-2a10726ecd4f)

In this link there is some explanation, but in this sensors the value returns to 0.
https://community.home-assistant.io/t/long-term-statistics-max-value-not-available/423889/3?u=jvsystelab
 
**To Reproduce**
Create a statistics card and select an entity (from the previos list).

**Expected behavior**
The card can be used as a sensor with all the configuration options

**Screenshots**
Above

**Comment by tijsverkoyen** [comment]
I think the comment in https://community.home-assistant.io/t/long-term-statistics-max-value-not-available/423889/4 is valid here.

These energy sensor are implemented as sensors with the `energy` device class, which need to have a state class of `total` or `total_increasing`.

From the [Home Assistant Documentation](https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes):

> Similar to total, with the restriction that the state represents a monotonically increasing positive total which periodically restarts counting from 0, e.g. a daily amount of consumed gas, weekly water consumption or lifetime energy consumption. Statistics of the accumulated growth of the sensor's value since it was first added is updated every 5 minutes. A decreasing value is interpreted as the start of a new meter cycle or the replacement of the meter.

The sensors are using `total_increasing` as they reset when the value is lower, which happens at the start of a new periode.


I suspect you want to display the average over a larger period? What you could try is use a helper (template) which uses the state of the energy sensor you want and set the device class to `measurement`. But this is untested.

**Comment by jvcsw** [comment]
What I want is to always show the maximum value of daily, monthly, annual production in kW.

**Comment by tijsverkoyen** [comment]
I don't understand what you are trying to do:

1. Energy is expressed in kWh, not in kW.
2. The values are the maximum, as they are only increasing. A lower value means a new period. As in: Total Current Day Energy will only increase during the day. Hence the "Total".

**Comment by jvcsw** [comment]
Yes, the h was missing.

I have this (daily peak, daily production, max daily production):
![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/fdbc6d97-fa33-469f-8c66-5a437cd4f2d4)

To get the third one I had to create a helper (template) of the "measurement" type. And of course, if it works, but I have to do the same for the weekly, monthly, annual and other integration sensors. Everything multiplies.

Is there a solution? Yes
But it would be nice if it were not necessary to create the helpers.

**Comment by tijsverkoyen** [comment]
I don't understand what you expect?

Are you asking me to change the sensors against how Home Assistant has documented? 
Are you asking to create extra entities with duplicate data?

In my opinion this is a feature request for Home Assistant, to make the average, max, mean, ... available for energy sensors with a state class of `total_increasing`.
