### ISSUE TITLE
Open Api Credentials error

### ISSUE THREAD

**Issue by jesusma32** [tijsverkoyen/HomeAssistant-FusionSolar#17]
Hi, I can log via web , with my open api credentials, but on home assistant config give me error.

Any ideas?

I try too adding region01, but no success.

Thanks

**Comment by tijsverkoyen** [comment]
What is the error? Is it the same as in https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/12?

**Comment by jesusma32** [comment]
No, if I access to the link no a browser, I put my login data and I can see all.
If I put my login data on Home Assistant on the assistant to add Fusión, give me wrong data login.



Enviado desde mi iPhone

El 25 nov 2022, a las 8:48, Tijs Verkoyen ***@***.***> escribió:

﻿

What is the error? Is it the same as in #12<https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/12>?

**Comment by tijsverkoyen** [comment]
I don't think that is an OpenAPI account. The OpenAPI credentials will not work on the Huawei Portal.
Have you contacted Huawei for OpenAPI credentials? If not: you can use the Kiosk mode.

**Comment by jesusma32** [comment]
Hi, I contact to Huawei, and offer to contact to my installer to créate the account, and gime me a manual.
I use the data login to Fusión App

Enviado desde mi iPhone

El 25 nov 2022, a las 9:18, Tijs Verkoyen ***@***.***> escribió:

﻿

I don't think that is an OpenAPI account. The OpenAPI credentials will not work on the Huawei Portal.
Have you contacted Huawei for OpenAPI credentials? If not: you can use the Kiosk mode.

**Comment by tijsverkoyen** [comment]
I really think you are using the credentials for the FusionSolar app as OpenAPI credentials. Which they don't are.

The credentials that you use for the Fusion Solar app on your phone, or to login to the [web portal](https://eu5.fusionsolar.huawei.com) are *not* OpenAPI credentials. These credentials can be used to retrieve the Kiosk URL which you can use in this integration by selecting Kiosk mode.

If you have contacted eu_inverter_support@huawei.com (as explained on https://forum.huawei.com/enterprise/en/communicate-with-fusionsolar-through-an-openapi-account/thread/591478-100027?page=5) they should have asked for the serial number of your inverted and answered with your OpenAPI credentials. Which can not be used to login in the Fusion Solar app nor the web portal. These OpenAPI credentials can be used in the integration if you choose the OpenAPI mode.

Maybe it would be beneficial if you clearly explain the steps you have done so far, and check if there are errors. Maybe with some screenshots.

**Comment by jesusma32** [comment]
Huawei send to me , and my dealer créate the account




Enviado desde mi iPhone

**Comment by tijsverkoyen** [comment]
I don't understand what Huawei send. Huawei is the only party who can create OpenAPI credentials. So again: which credentials are you talking about?

1. Credentials for the Fusion Solar app (on your phone). 
2. OpenAPI credentials that are provided by Huawei Support.

If option 1: these are **NOT** OpenAPI credentials and can **NOT** be used with the OpenAPI mode of this integration, choose the Kiosk mode.

If option 2: which exact error do you get in Home Assistant?

**Comment by jesusma32** [comment]
Now Fusión with Open Api works.

But instant produce no.

Enviado desde mi iPhone

El 25 nov 2022, a las 12:57, Tijs Verkoyen ***@***.***> escribió:

﻿

I don't understand what Huawei send. Huawei is the only party who can create OpenAPI credentials. So again: which credentials are you talking about?

  1.  Credentials for the Fusion Solar app (on your phone).
  2.  OpenAPI credentials that are provided by Huawei Support.

If option 1: these are NOT OpenAPI credentials and can NOT be used with the OpenAPI mode of this integration, choose the Kiosk mode.

If option 2: which exact error do you get in Home Assistant?

**Comment by jesusma32** [comment]
Enviado desde mi iPhone

**Comment by tijsverkoyen** [comment]
Ok, send me the OpenAPI credentials through mail at `fusionsolar [at] verkoyen.eu` and I will try to debug.

**Comment by tijsverkoyen** [comment]
@jesusma32 I am closing this issue as there is not much I can do at the moment. Feel free to reopen if you think otherwise.
If Huawei has resolved the issue: let me know so we can document this in this issue for other people.
