### ISSUE TITLE
Some sensors take previous values at midnight

### ISSUE THREAD

**Issue by jvcsw** [tijsverkoyen/HomeAssistant-FusionSolar#172]
**Describe the bug**
Some sensors returns to the previous value at midnight.

* Are you using the latest version of Home Assistant? 
Yes
* Are you using the latest version of this integration? 
Yes
* Have you looked into the closed issues and did not find a similar issue.
Yes
* Are you using Kiosk or Northbound / OpenAPI mode? 
Northbound

**To Reproduce**
1. Go to sensor 'Total Lifetime Energy'
2. See statistics graph

**Expected behavior**
The graph never decrease (Total Lifetime Energy sensor)
The graph doesn't decrease in middle of the month (Total Current Month Energy sensor)

**Screenshots**
![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/cbc0950b-aeaa-40d3-a4c8-14349622712b)

![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/94a635ae-0d88-4b1d-ac7d-e5d56865a326)

**Comment by tijsverkoyen** [comment]
Yeah, this is a "known" issue with the data that Huawei returns. I won't fix this.

See:

- https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/159
- https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/138 (your ticket btw)
- https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/135
- https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/129

**Comment by jvcsw** [comment]
But, a possible solution could be to not update the sensor if the new value is smaller than the current value, right?
