### ISSUE TITLE
Not all kiosk sensors are present in Home assistant

### ISSUE THREAD

**Issue by somar12** [tijsverkoyen/HomeAssistant-FusionSolar#173]
** Debug information **
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant? **Yes**
* Are you using the latest version of this integration? **Yes**
* Have you looked into the closed issues and did not find a similar issue? **Yes**
* Are you using Kiosk or Northbound / OpenAPI mode? **Kiosk**
* If you are using Kiosk mode. Have you checked that the url is still valid? **Yes** 
See [I am using the kiosk mode, but the data is not updating](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#i-am-using-the-kiosk-mode-but-the-data-is-not-updating)
* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. See [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#how-can-i-verify-my-northbound-api--openapi-credentials)
* Have you checked the logs for any info? **Yes** 

I've made kiosk integration.

Only have five entities:
total_lifetime_energy
total_current_year_energy
total_current_day_energy
total_current_month_energy
realtime_power

I can't find:
sensor.xxx_reverse_active_energy
sensor.xxx_active_energy_forward_active_energy
and
sensor.xxx_charging_capacity
sensor.xxx_discharging_capacity

Can you please tell me if this was expected after integration via Kiosk?

** Debug information **
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant? **Yes**
* Are you using the latest version of this integration? **Yes**
* Have you looked into the closed issues and did not find a similar issue? **Yes**
* Are you using Kiosk or Northbound / OpenAPI mode? **Kiosk**
* If you are using Kiosk mode. Have you checked that the url is still valid? **Yes** 
See [I am using the kiosk mode, but the data is not updating](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#i-am-using-the-kiosk-mode-but-the-data-is-not-updating)
* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. See [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#how-can-i-verify-my-northbound-api--openapi-credentials)
* Have you checked the logs for any info? **Yes** 

**To Reproduce** 

**Expected behavior**

**Screenshots**

**Comment by tijsverkoyen** [comment]
Kiosk does not expose all this data. Kiosk exposes only a limited amount of entities.

**Comment by somar12** [comment]
> Kiosk does not expose all this data. Kiosk exposes only a limited amount of entities.

Ok. 
Northbound API / OpenAPI probably provides a more complete integration.
Thank you Tijsverkoyen
