### ISSUE TITLE
Possible to adjust 'Active Power Adjustment'?

### ISSUE THREAD

**Issue by pdb01** [tijsverkoyen/HomeAssistant-FusionSolar#175]
Hi!

Thank you for this great integration.

**Describe the bug**
Not a bug, but capability question...

I have a 'dynamic pricing' tarif and lately there are many moments when electricity prices are negative and solar infeed costs money, in which case it is interesting to adjust the active power infeed from the inverter to (near) zero.
Luckily, this can be done through the website https://eu5.fusionsolar.huawei.com/ by adjusting this with a button "Active Power Adjustment" on the monitoring / inverter page.

I was wondering if there is a way to achieve this from within Home-Assistant on an API-basis... 
I fear not as - in my limited knowledge - we only get information out of the system, but not writing. 

** Debug information **
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant? Yes
* Are you using the latest version of this integration? Yes
* Have you looked into the closed issues and did not find a similar issue. Yes
* Are you using Kiosk or Northbound / OpenAPI mode? Northbound / OpenAPI
* If you are using Kiosk mode. Have you checked that the url is still valid? See [I am using the kiosk mode, but the data is not updating](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#i-am-using-the-kiosk-mode-but-the-data-is-not-updating)
* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. See [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#how-can-i-verify-my-northbound-api--openapi-credentials) N/A
* Have you checked the logs for any info? N/A

**To Reproduce**
N/A

**Expected behavior**
 This would be a great extra feature as then we could make easy integrations in Home Assistant to automate these power adjustments instead of having to do it manually every X days/weeks.
If not possible, could be interesting to know where and how to ask (as I believe competitor inverter brands do allow this already...)

**Screenshots**
N/A

**Comment by tijsverkoyen** [comment]
At this point the integration only reads data. At this point I want to keep it that way.

**Comment by tijsverkoyen** [comment]
If you really need this. I think https://github.com/wlcrs/huawei_solar supports it.

**Comment by pdb01** [comment]
Ok, as I thought. Thanks.
This other integration needs extra hardware, I believe (dongle etc?).

I will stick to the manual follow-up for now :-)

Thanks a lot
Pieter
