### ISSUE TITLE
login issue with the Northbound API

### ISSUE THREAD

**Issue by tomazzive** [tijsverkoyen/HomeAssistant-FusionSolar#176]
Hello, 

I see this error in the log of HA:

> 2024-06-26 10:15:43.697 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up fusion_solar platform for sensor
> File "/config/custom_components/fusion_solar/fusion_solar/openapi/openapi_api.py", line 47, in login
> raise FusionSolarOpenApiError(f'Could not login with given credentials')
> custom_components.fusion_solar.fusion_solar.openapi.openapi_api.FusionSolarOpenApiError: Could not login with given credentials

I tried to login in Postman and get an error that API can not be found. I double checked the URL prefix. It was set to eu5, but if I login to the web dashboard, I'm forwarded to uni001eu5. Yet I get a 404 if I use the /thirdData url. So I assume eu5 is still correct. 

More users having problem to login in the Northbound API? 
Probably a fart in a mesh bag; Or the supplier that messed up my API account.

**Comment by fetredlwl** [comment]
I have exactly the same issue since yesterday.
Tried to validate my credentials via curl with the response: ACCESS_FREQUENCY_IS_TOO_HIGH

**Comment by delavegan** [comment]
Same problem since 25/06/2024

**Comment by furora** [comment]
Same here since 25/06/2024

**Comment by fetredlwl** [comment]
I Just restarted HA and IT IS working again. For me it looks like there has been an issue at Huawei.

**Comment by baizinger** [comment]
Same issue here. Restarting does not help.

**Comment by LJ-Stevo** [comment]
I don't know if I have to open a new issue for that (cause I'm a noob), but I'm getting my information via the Kiosk option.
But also since yesterday it's giving me "zero" as outcome for the entities : "realtime_power" and "Total Current Day Energy".
So now, I don't have any results in my energy dashboard.

**Comment by theRoundGreek** [comment]
> I don't know if I have to open a new issue for that (cause I'm a noob), but I'm getting my information via the Kiosk option. But also since yesterday it's giving me "zero" as outcome for the entities : "realtime_power" and "Total Current Day Energy". So now, I don't have any results in my energy dashboard.

same exact issue for me

**Comment by baizinger** [comment]
I'm not an expert, but i think there might be an issue with the connection to hacs or github. i'm having troubles with another hacs integration (waste bin update) + esphomeupdate for my slimmelezer. So 2 components which are getting their stuff from github doesnt work as well.

**Comment by AndersHoglund** [comment]
> I don't know if I have to open a new issue for that (cause I'm a noob), but I'm getting my information via the Kiosk option. But also since yesterday it's giving me "zero" as outcome for the entities : "realtime_power" and "Total Current Day Energy". So now, I don't have any results in my energy dashboard.

Seems to be an issue with Hawei kiosk servers. I also have not received any good data for a few days via kiosk.  This problem also exists in the ordinary FusionSolar kiosk web site, nothing unique for HA or this integration.Tried renewing my kiosk-id, since it is only valid for one year, but that did not help. But I did get one, yes 1, new data point update in kiosk. It turns out you get one kiosk server side update each time you login to your account and view the kiosk URL. No need to change kiosk-id or URL, just view it and press OK and the kiosk view will make one update. Data on you account monitor page is always uptodate, only the kiosk page is not updating automatically.
Discussing kiosk in this thread/issue is a bit off topic, sorry. And it is also most likely a Hauwei issue, not a HA issue.

**Comment by MichelDuTilleul** [comment]
Same problem .... :-(

**Comment by AndersHoglund** [comment]
We are at least three users having problem with FusionSolar Kiosk. I will open a separate issue for this case, so it may be easier for others to find it.
/A

**Comment by didierlebon** [comment]
> We are at least three users having problem with FusionSolar Kiosk. I will open a separate issue for this case, so it may be easier for others to find it. #178 /A

at least 4 : same issue for me.

**Comment by NickBootOne** [comment]
Here same issue with the API connect, last data is from 25 June at 17:50

**Comment by tijsverkoyen** [comment]
> I have exactly the same issue since yesterday. Tried to validate my credentials via curl with the response: ACCESS_FREQUENCY_IS_TOO_HIGH

This error means you are running into rate limiting.
Do you have multiple integrations/scripts/... using the same credentials?
Try to disable the integration and try the curl call again after a few hours.

> Here same issue with the API connect, last data is from 25 June at 17:50

Do you see any error message in the logs?

**Comment by fetredlwl** [comment]
>> I have exactly the same issue since yesterday. Tried to validate my credentials via curl with the response: ACCESS_FREQUENCY_IS_TOO_HIGH

>This error means you are running into rate limiting.
Do you have multiple integrations/scripts/... using the same credentials?
Try to disable the integration and try the curl call again after a few hours.

No I'm just running the this integration with the credential for the northbound api.

I did the following to get it running again:
1. Set "update_interval=timedelta(seconds=600)" in sensor.py to update_interval=timedelta(seconds=3600)"
2. Restart HA -> Still get the error
3. Waited for a couple of hours
4. Restart HA -> Works again
5. Reset the update interval back to 600 and restarted again
6. No issues in the last couple of days

**Comment by NickBootOne** [comment]
Disabled the plugin for a day, restarted Home Assistant after disabling.
Then enabled the next day with an restart.
Now everything works 🤔

**Comment by tijsverkoyen** [comment]
@tomazzive, @delavegan, @furora, @baizinger, @MichelDuTilleul, @didierlebon I will close this issue. If this is still an issue: let me know.

**Comment by MichelDuTilleul** [comment]
It’s OK for me. Thanks.
