### ISSUE TITLE
FusionSolar Kiosk server side is not updating automatically.

### ISSUE THREAD

**Issue by AndersHoglund** [tijsverkoyen/HomeAssistant-FusionSolar#178]
Seems to be an issue with Hawei kiosk servers. I have not received any good data for a few days via kiosk. This problem also exists in the ordinary FusionSolar kiosk web site, nothing unique for HA or this integration.Tried renewing my kiosk-id, since it is only valid for one year, but that did not help. But I did get one, yes 1, new data point update in kiosk. It turns out you get one kiosk server side update each time you login to your account and view the kiosk URL. No need to change kiosk-id or URL, just view it and press OK and the kiosk view will make one update. Data on your account monitor page is always uptodate, only the kiosk page is not updating automatically.
/A

**Comment by argovaerts** [comment]
I seem to have opened an issue about the same problem at about the same time as you #179, so will close mine

**Comment by AndersHoglund** [comment]
> I seem to have opened an issue about the same problem at about the same time as you #179, so will close mine

Might be the same root cause, but you have other symptons. I can not see any problems in my logs. Keep your issue open please.

**Comment by AndersHoglund** [comment]
I did send a mail to Huawei support (eu_inverter_support@huawei.com) only to get a robot reply to create a service request. :-(
I have not done that...yet. Anyone else done that?
/A

**Comment by iltisjim** [comment]
I have the same problem. No data is updated.

**Comment by AndersHoglund** [comment]
I have now filed a service request with Huawei. I suggest everyone with this issue do the same.
First, login to your FusionSolar account and find the mail address to your support contact, most likely same as mine: eu_inverter_support@huawei.com Second, send a short description of this problem. You will get a robot mail with a link to a service request form, fill it in and submit it. You may copy&paste my first post as the problem description.
/A

**Comment by PieterJanCoeckelbergh** [comment]
Same issue, I've filed a service request at Huawei.

**Comment by iltisjim** [comment]
Me too

**Comment by tijsverkoyen** [comment]
To be clear: This seems to be a Huawei Issue. I can't do nothing about it. 

**I strongly suggest to create a service request, as @AndersHoglund said.** 
See: https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/178#issuecomment-2198630739

**Comment by AndersHoglund** [comment]
Still the same today. Last Kiosk update was yesterday at 12:00
I have got a Huawei Support contact now, sent them a few screenshots too.
/A 
![FusioSolar_Kiosk_page_20240702](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/15121917/7c69677c-66a2-46db-954c-03e0f7f11700)

**Comment by argovaerts** [comment]
I opened a service request as well. Currently not getting any helpful reaction

**Comment by LucVerhelst** [comment]
Same problem sinds yesterday 15:31:06 h. 
I opened a service request.

**Comment by hoburgt** [comment]
Same problem here since a few days. Kiosk page is looking normal but HA is not getting any updates.

**Comment by AndersHoglund** [comment]
> Same problem here since a few days. Kiosk page is looking normal but HA is not getting any updates.

If the Kiosk page looks normal and is updating every 30 minute as usual, you do NOT have this problem. Something else. Restart HA.
/A

**Comment by AndersHoglund** [comment]
> My ticket is being handled by _Huawei Solar Inverter Global Service Center Romania_. It might be worth to check if they different tickets aren't being processed by different people.

My ticket handler is: 
Gheorghios Maroulas (Service Engineer, Romania TAC) (gheorghios.maroulas@huawei.com)
With:
Helpdesk Leader– Corina Pirvu [corina.elena.pirvu@huawei.com](mailto:corina.elena.pirvu@huawei.com)
 
/A

**Comment by hoburgt** [comment]
> > Same problem here since a few days. Kiosk page is looking normal but HA is not getting any updates.
> 
> If the Kiosk page looks normal and is updating every 30 minute as usual, you do NOT have this problem. Something else. Restart HA. /A

Well, it looks normal but it is not updating at all. I even reinstalled Fusion Solar which didn't resolve the issue. I guess I have to write to Huawei support also about the issue (just did a minute ago...).

**Comment by TheMoonMan00** [comment]
I also have this problem and send an e-mail to support.

**Comment by iltisjim** [comment]
Hi

I got this answer 

Hello,

 

Please upgrade the Dongle to the latest firmware and also the inverter and let us know if this will solve the issue.

At home i will Look how i do it.

**Comment by peterpanxiii** [comment]
Hi iltisjim
Same problem here since 01.07.2024 Kiosk page is looking normal but HA is not getting any updates.
Several restarts of HA did not help. Was just about to downgrade HA from 2024.6.4 to 2024.6.3 when I hit this thread. Meanwhile I think, it's not a HA, but a Huawei problem. I am pretty curious, whether upgrading the firmware of the dongle and inverter will help. Please report how it went.
Muchas Gracias

**Comment by argovaerts** [comment]
Just got a response from benelux service. They expect a solution from R&D tomorrow.

**Comment by SimoneRullo** [comment]
However, this story that the first level support always proposes the usual turn off-on-update solution is embarrassing.  I would say that in 2024 everyone tries that route before writing to technical support.... reiterating it is an obvious and useless attempt to stall while they try to understand what the heck happened.

**Comment by hoburgt** [comment]
> However, this story that the first level support always proposes the usual turn off-on-update solution is embarrassing. I would say that in 2024 everyone tries that route before writing to technical support.... reiterating it is an obvious and useless attempt to stall while they try to understand what the heck happened.

Yes, totally agree to that. The first reply I got was the procedure describing how to set up an owner account which, what they could have seen, was already in place since the installation of our solar panels. Later on I tried the suggestion to force a 
complete new kiosk link which I did with, again, a renewed installation of the Fusion Solar plugin for HA. That all didn't solve anything and this morning the kiosk page still shows the values from yesterday morning...
In addition, I installed the latest HA (2024.7.0) this morning and get the following warning(s)"

> Logger: homeassistant.helpers.frame
Bron: helpers/frame.py:184
Eerst voorgekomen: 08:09:05 (1 gebeurtenissen)
Laatst gelogd: 08:09:05
Detected that custom integration 'fusion_solar' calls async_forward_entry_setup for integration, fusion_solar with title: Fusion Solar and entry_id: 181cac2ca15499ecaab0be9bed61d849, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/fusion_solar/__init__.py, line 23: hass.async_create_task(, please create a bug report at https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues

**Comment by LucVerhelst** [comment]
FYI:
> There is a known issue about the Kiosk, I have noted all the cases related. R&D is working on the case.
> We will keep you informed.
> Maria Muniáin Pàmies (Netherlands TAC)

**Comment by AndersHoglund** [comment]
> FYI:
> 
> > There is a known issue about the Kiosk, I have noted all the cases related. R&D is working on the case.
> > We will keep you informed.
> > Maria Muniáin Pàmies (Netherlands TAC)

You seem to have found a good support contact. 
While at it, could you remind them to also fix the midnight glitches, issue #135 .
/A

**Comment by TheMoonMan00** [comment]
Benelux support:

Dear customer,
 
We are experiencing issues with kiosk currently. We expect to resolve this issue in 2 working days.
 
Please try again later.

**Comment by AndersHoglund** [comment]
I started getting Kiosk data every 30 minutes as usual this morning at 04:10. 
If this keeps up all day, I will close this case.
/A

**Comment by hoburgt** [comment]
> I started getting Kiosk data every 30 minutes as usual this morning at 04:10. If this keeps up all day, I will close this case. /A

Yes, also for me it looks like to be working normally again (Belgium). I am going to report back to the Huawei support who kept me informed that all seems fine again! Nice!!

**Comment by PieterJanCoeckelbergh** [comment]
Same here (also Belgium), everything is working. I will wait for the full day of data to report back just to be sure. 
Great joint effort of barraging Huawei with support tickets :)

**Comment by Xehinz** [comment]
I have been following this issue and i can confirm everything is working again as well here (also Belgium).

**Comment by AndersHoglund** [comment]
Yes, working as usual, midnight glitch and all. Closing this issue now
![Screenshot 2024-07-05 a](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/15121917/360e54d0-689f-4136-964c-b13057039cc8)

**Comment by peterpanxiii** [comment]
Same here. Looks good

**Comment by Nabys** [comment]
It doesn't look good here. The kiosk is updating, and the data is received by HA, but whenever HA receives a new data point, it overrides the previous one. Not sure if that's the right terminology. 

So the HA history only shows the latest data point and not the previous ones.

**Comment by LucVerhelst** [comment]
> It doesn't look good here. The kiosk is updating, and the data is received by HA, but whenever HA receives a new data point, it overrides the previous one. Not sure if that's the right terminology.
> 
> So the HA history only shows the latest data point and not the previous ones.

I can see the full history of the entity, 1 change every 30 minutes.

**Comment by Nabys** [comment]
> > It doesn't look good here. The kiosk is updating, and the data is received by HA, but whenever HA receives a new data point, it overrides the previous one. Not sure if that's the right terminology.
> > So the HA history only shows the latest data point and not the previous ones.
> 
> I can see the full history of the entity, 1 change every 30 minutes.

That's great, but I can't. 

This is what I see in HA, even though the kiosk is updating as normal : 
![IMG_7177](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/96481020/2bd09638-5222-4c76-941d-09bc2099152b)


That is the latest data point received and it erased the previous ones.

**Comment by LucVerhelst** [comment]
> > > It doesn't look good here. The kiosk is updating, and the data is received by HA, but whenever HA receives a new data point, it overrides the previous one. Not sure if that's the right terminology.
> > > So the HA history only shows the latest data point and not the previous ones.
> > 
> > 
> > I can see the full history of the entity, 1 change every 30 minutes.
> 
> That's great, but I can't.
> 
> This is what I see in HA, even though the kiosk is updating as normal : ![IMG_7177](https://private-user-images.githubusercontent.com/96481020/346077685-2bd09638-5222-4c76-941d-09bc2099152b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNzE5NDQsIm5iZiI6MTcyMDE3MTY0NCwicGF0aCI6Ii85NjQ4MTAyMC8zNDYwNzc2ODUtMmJkMDk2MzgtNTIyMi00Yzc2LTk0MWQtMDliYzIwOTkxNTJiLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQwOTI3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTBkN2M1OWY3MjA5ODVlYTQyMjEwODY1ZGVhY2FlMmNkZjBhOTQ3ZTkyZDVjMmUwZjBmZDVjOGJhMzIzYzc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vdAtkYcxmwNApsYAhwy1N9md604K0Eo7b_cJLcl7Hgo)
> 
> That is the latest data point received and it erased the previous ones.

Do you get the full history in the Huawei kiosk?
![2024-07-05 11_29_10-uni002eu5 fusionsolar huawei com_pvmswebsite_nologin_assets_build_cloud html#_ki](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/42475052/1d9fdd20-4127-4b5e-858a-c5f55902539b)

**Comment by Nabys** [comment]
> > > > It doesn't look good here. The kiosk is updating, and the data is received by HA, but whenever HA receives a new data point, it overrides the previous one. Not sure if that's the right terminology.
> > > > So the HA history only shows the latest data point and not the previous ones.
> > > 
> > > 
> > > I can see the full history of the entity, 1 change every 30 minutes.
> > 
> > 
> > That's great, but I can't.
> 
> Do you get the full history in the Huawei kiosk? 

Yes, I do:
![IMG_7178](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/96481020/9a403484-793a-4c4b-8317-a8cc591d96cb)


I've restarted HA in case that would help but it doesn't.

**Comment by LucVerhelst** [comment]
> > Do you get the full history in the Huawei kiosk?
> 
> Yes, I do: 
> 
> I've restarted HA in case that would help but it doesn't.

Then it's a different problem, not related to the Huawei-problem. You should open a new issue here on github.
