### ISSUE TITLE
Attribute not in coordinator data

### ISSUE THREAD

**Issue by argovaerts** [tijsverkoyen/HomeAssistant-FusionSolar#179]
**Describe the bug**
Data only loads exactly one time per day for the last few days. Tried already the following:
1. Restart HA
2. Disabled and enabled device
3. Disabled and enabled hub
4. Removed and re-added hub, first with same Kiosk URL, later with a new one

**Debug information**
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant? Yes
* Are you using the latest version of this integration? Yes
* Have you looked into the closed issues and did not find a similar issue.
Issue is a bit similar to #165 

* Are you using Kiosk or Northbound / OpenAPI mode? Kiosk
* If you are using Kiosk mode. Have you checked that the url is still valid? See [I am using the kiosk mode, but the data is not updating](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#i-am-using-the-kiosk-mode-but-the-data-is-not-updating) Yes
* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. See [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#how-can-i-verify-my-northbound-api--openapi-credentials)
* Have you checked the logs for any info? 

**Screenshot and logs**
```
Logger: custom_components.fusion_solar.fusion_solar.energy_sensor
Source: custom_components/fusion_solar/fusion_solar/energy_sensor.py:67
integration: FusionSolar (documentation, issues)
First occurred: 06:25:04 (404 occurrences)
Last logged: 17:25:04

Attribute dailyEnergy not in coordinator data
Attribute monthEnergy not in coordinator data
Attribute yearEnergy not in coordinator data
Attribute cumulativeEnergy not in coordinator data
```

```
Logger: custom_components.fusion_solar.fusion_solar.kiosk.kiosk_api
Source: custom_components/fusion_solar/fusion_solar/kiosk/kiosk_api.py:46
integration: FusionSolar (documentation, issues)
First occurred: 06:25:03 (141 occurrences)
Last logged: 17:45:04

Retrieving the data failed. Raw response: {"data":"neteco.pvms.systemSetting.notExist","success":false,"failCode":0}
```

![Screenshot from 2024-06-29 18-17-01](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/3484590/737daa81-d383-42e9-b2d1-3236b9c143b8)

**Comment by argovaerts** [comment]
Duplicate

**Comment by tijsverkoyen** [comment]
The error is: `Retrieving the data failed. Raw response: {"data":"neteco.pvms.systemSetting.notExist","success":false,"failCode":0}`

I would suspect that your Kiosk URL is not valid anymore. Have you checked that the Kiosk page is still working? And if so would you be able to share the url please?

**Comment by argovaerts** [comment]
[Kiosk URL](https://uni002eu5.fusionsolar.huawei.com/pvmswebsite/nologin/assets/build/cloud.html#/kiosk?kk=DmfCyddesm9fOcpsn3B4oxzNIsQwnN9u) seems to be working fine.

**Comment by Nabys** [comment]
I think I have the same issue, although part of it also is similar to the behaviour of 178. 

I refreshed the kiosk url just in case, and removed and re-added the integration with the new url. 

The values in HA do not update, but as the author of 178 says, if you go to the kiosk url page and click ok, it'll refresh in HA, as a brand new data point: eg the previous data point is gone. 

The data on the kiosk seems to be correct though, it shows today's usage as normal. 

I don't know how to find the logs otherwise I'd add them, sorry

**Comment by Nabys** [comment]
> @Nabys your issue is probably #178. Which seems/is different then @argovaerts

Thanks, I wasn't sure as my kiosk does seem to update normally unlike the other people in 178.

**Comment by argovaerts** [comment]
Working fine again. Just had to restart HA once (energy total lifetime kept being unknown). Solution of #178 seemed to work here as well. I will close the issue.
