### ISSUE TITLE
Energy Dashboard - "last_reset" is missing

### ISSUE THREAD

**Issue by EbbiKS** [tijsverkoyen/HomeAssistant-FusionSolar#18]
Hello,

I am using the following entities for the Home Assistant Energy Dashboard: 
- sensor.power_sensor_reverse_active_energy
- sensor.power_sensor_active_energy_forward_active_energy
- sensor.battery_discharging_capacity
- sensor.battery_charging_capacity

Unfortunately, the values do not seem to be interpreted correctly. The following message is displayed in the dashboard settings: 

"The following entities have state class "measurement", but "last_reset" is missing: sensor.power_sensor_reverse_active_energy
sensor.power_sensor_active_energy_forward_active_energy"

Is it possible to add this "last_reset" attribute or what can be the reason that the calculation in the Energy Dashboard does not work correctly?

**Comment by tijsverkoyen** [comment]
In the documentation charging and discharing capacity have the unit of kWh, but I'n not sure if that is correct. Could you check if the unit is correct? Are these values changing, or are these fixed?

To be honest I don't understand why HA repots this, as last_reset is `None` per default.

Would you be able to test by making the changes in https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/19/files manually in your local installation and report back if this fixes the issue?

Which version of HA are you using?

**Comment by EbbiKS** [comment]
kw/h is correct in my opinion. The total values must be entered. (Total drawn from the grid or fed). Based on the differences, the dashboard then calculates the daily values. The same logic is used for the Battery. 

I have implemented your change, unfortunately, then the whole extension no longer works. I have attached the error message from the log.  I use the latest Home Assistant version: 

Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest


Error 1: 
Logger: homeassistant.setup
Source: setup.py:320 
First occurred: 11:17:34 (2 occurrences) 
Last logged: 11:17:34

Unable to prepare setup for platform fusion_solar.sensor: Platform not found (Exception importing custom_components.fusion_solar.sensor).


Error 2: 
Logger: homeassistant.loader
Source: custom_components/fusion_solar/fusion_solar/realtime_device_data_sensor.py:175 
Integration: FusionSolar (documentation, issues) 
First occurred: 11:17:34 (2 occurrences) 
Last logged: 11:17:34

Unexpected exception importing platform custom_components.fusion_solar.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/fusion_solar/sensor.py", line 30, in <module>
    from .fusion_solar.realtime_device_data_sensor import *
  File "/config/custom_components/fusion_solar/fusion_solar/realtime_device_data_sensor.py", line 161, in <module>
    class FusionSolarRealtimeDeviceDataEnergySensor(FusionSolarRealtimeDeviceDataSensor):
  File "/config/custom_components/fusion_solar/fusion_solar/realtime_device_data_sensor.py", line 175, in FusionSolarRealtimeDeviceDataEnergySensor
    def last_reset(self) -> datetime | None:
TypeError: unsupported operand type(s) for |: 'module' and 'NoneType'

**Comment by tijsverkoyen** [comment]
Hmm, which version of HA are you using?
I have updated https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/19/files, could you try again?

**Comment by tijsverkoyen** [comment]
Very weird. As I explicitly set it to None, and the default is None.
Could you share a screenshot of the configuration of the Energy Dashboard? Are you willing to share your OpenAPI credentials with me (via mail: `fusionsolar [at] verkoyen.eu`). So I can debug it myself?

**Comment by EbbiKS** [comment]
<img width="1146" alt="Bildschirm­foto 2022-12-06 um 14 47 48" src="https://user-images.githubusercontent.com/107893509/205929420-eace4dc2-3b6d-43e3-a6e7-e3824c96892f.png">

Do you think this is a problem that only affects me and not a general one?

**Comment by tijsverkoyen** [comment]
The problem is that I don't have a battery, so I don't have the entities that you have configured. 

I developed the parts for batteries based on the documentation of Huawei and Home Assistant. It would help fit you share your OpenAPI credentials so I can debug and see the problem on my debug-setup so I can try to resolve the issue. But no hard feelings if you don't want to share them.

**Comment by tijsverkoyen** [comment]
Yeah, did a new release. Hope it is resolved now. But I don't see the warning in the Energy configuration anymore. @EbbiKS would you please be so kind to let me know if the issue is resolved after you have update to [v2.1.2](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/releases/tag/v2.1.2)

**Comment by EbbiKS** [comment]
Perfect, now it runs as it should! Thank you!
