### ISSUE TITLE
Realtime Power shows 0 since 4 days

### ISSUE THREAD

**Issue by kszabi2024** [tijsverkoyen/HomeAssistant-FusionSolar#180]
**Describe the bug**
Since 4 days the realtime power is showing 0. In my mobile app for huawei shows the real value.

** Debug information **
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant?
* yes
* Are you using the latest version of this integration?
* yes
* Have you looked into the closed issues and did not find a similar issue.
* yes
* Are you using Kiosk or Northbound / OpenAPI mode?
* dont know
* If you are using Kiosk mode. Have you checked that the url is still valid? See [I am using the kiosk mode, but the data is not updating](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#i-am-using-the-kiosk-mode-but-the-data-is-not-updating)
* * dont know
* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. See [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#how-can-i-verify-my-northbound-api--openapi-credentials)
* Have you checked the logs for any info? 
* no

**To Reproduce**

**Expected behavior**
It is expected to show the real value of the realtime power

**Screenshots**
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/174415115/a68a78d1-465e-41ab-a392-b1ea002de0b9)

**Comment by tijsverkoyen** [comment]
Check if you are using Kiosk or Northbound. I guess you have the same issue as https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/178 or https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/176.
