### ISSUE TITLE
Received data points from Kiosk Override HA History

### ISSUE THREAD

**Issue by Nabys** [tijsverkoyen/HomeAssistant-FusionSolar#181]
**Describe the bug**
Now that #178 is fixed, my HA is receiving kiosk data again, but every received data point overrides the previous, which means no history is being build. 

So eg the real time power sensor only every shows the latest data point of max 30 mins old and nothing before that. 

** Debug information **
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant? 2024.6.4
* Are you using the latest version of this integration? Yes
* Have you looked into the closed issues and did not find a similar issue. Kind of related to 178
* Are you using Kiosk or Northbound / OpenAPI mode? Kiosk 
* If you are using Kiosk mode. Have you checked that the url is still valid? See [I am using the kiosk mode, but the data is not updating](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#i-am-using-the-kiosk-mode-but-the-data-is-not-updating) yes, I updated the kiosk url in relation to 178
* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. See [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#how-can-i-verify-my-northbound-api--openapi-credentials)
* Have you checked the logs for any info? No as I don't know where to find them 

**To Reproduce**

**Expected behavior**
With every data point received from the kiosk, HA builds a history of the points, instead of only recording the latest one. 

The below screenshots look the same, but they're at different kWh and they show that no history is recorded. 
![IMG_7177](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/96481020/4769706d-8023-4ed1-ac3d-5e6e7f9cffbd)
![IMG_7179](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/96481020/99983312-c4c9-43a2-8ad3-e4f91d04dc0b)

**Screenshots**

**Comment by LucVerhelst** [comment]
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/42475052/9fbd942b-4317-4f55-91de-01dfaeac9807)

You can switch on debug logging on the integration page.

**Comment by Nabys** [comment]
Thank you. It comes up with this:

`2024-07-05 12:39:11.133 DEBUG (MainThread) [custom_components.fusion_solar.fusion_solar.kiosk.kiosk] calculated API base url for ABCDE: https://uni004eu5.fusionsolar.huawei.com
2024-07-05 12:39:11.134 DEBUG (MainThread) [custom_components.fusion_solar.sensor] fusion_solar
2024-07-05 12:39:11.134 DEBUG (MainThread) [custom_components.fusion_solar.sensor] ABCDE
2024-07-05 12:39:11.675 DEBUG (SyncWorker_9) [custom_components.fusion_solar.fusion_solar.kiosk.kiosk_api] Received data for ABCDE:
2024-07-05 12:39:11.676 DEBUG (SyncWorker_9) [custom_components.fusion_solar.fusion_solar.kiosk.kiosk_api] {'realTimePower': 1.343, 'cumulativeEnergy': 11742.800000000001, 'monthEnergy': 86.11, 'dailyEnergy': 11.120000000000001, 'yearEnergy': 2720.17}
2024-07-05 12:39:11.679 DEBUG (MainThread) [custom_components.fusion_solar.sensor] Finished fetching FusionSolarKiosk data in 0.545 seconds (success: True) `

And this gets repeated every 10 mins.

**Comment by Nabys** [comment]
I also tried removing the integration completely and adding it again which hasn't worked. Still HA only ever shows 1 data point and the previously reported point is no longer available.

**Comment by Nabys** [comment]
I'm closing this as I'm a complete noob and this is totally a me issue and not anything to do with the integration. Sorry! (When re-adding the integration I renamed the sensors differently by accident and seeing I have several things excluded from the recorder, these were now also excluded...)
