### ISSUE TITLE
Missing sensors with Emma-A02

### ISSUE THREAD

**Issue by alexdess** [tijsverkoyen/HomeAssistant-FusionSolar#184]
**Describe the bug**
Hello, I just configured the API, with my installer, unfortunately I don't have these described entities:

- sensor.xxx_reverse_active_energy
- sensor.xxx_active_energy_forward_active_energy
- sensor.xxx_total_current_day_energy
- Battery energy in is given by sensor.xxx_charging_capacity
- Battery energy out is given by sensor.xxx_discharging_capacity

** Debug information **

- Huawei SUN2000-12KTL-MB0
- Huawei Emma-A02

I can only assume that this comes from EMMA, which wouldn't give the information in the same way. 
I don't have a battery at the moment.

* Are you using the latest version of Home Assistant? YES
* Are you using the latest version of this integration? YES
* Have you looked into the closed issues and did not find a similar issue?  YES
* Are you using Kiosk or Northbound / OpenAPI mode? Northbound mODE
* If you are using Northbound / OpenAPI mode. Check if your credentials are still valid. it is (created today to 2099).
* Have you checked the logs for any info? 

**To Reproduce**
1. Go to Energy configuration
2. Try to set the grid consumption

**Expected behavior**
See something with reverse_active_energy in the list.

**Screenshots**
![image](https://github.com/user-attachments/assets/b9020832-5135-459e-a80d-0b9586bcc55c)

**Comment by tijsverkoyen** [comment]
@alexdess I don't know how the Huawei Emma-A02 works. 
If you are willing to share your Northbound API credentials with me (`ha-fusion-solar [at] verkoyen [dot] eu`) I can look into it.

**Comment by alexdess** [comment]
Hello,

Thank you for your help, it’s definitely possible. The installers are coming to install a battery on August 20th.

Would it be better for you to wait until the battery is installed, or does it not make a difference for retrieving the data?

Also, I have a "live data" button that I can click to eliminate the one-minute delay. Let me know if you’d like to incorporate that and if it's possible to do so through the API. It seems that this button does not exist with the standard smart meter.

![image](https://github.com/user-attachments/assets/e2bba32f-8b43-43e2-a674-785167cead75)

**Comment by tijsverkoyen** [comment]
Any update?

**Comment by alexdess** [comment]
I was waiting for you to answer my question :).
```
Would it be better for you to wait until the battery is installed, or does it not make a difference for retrieving the data?
```

Since then I've had my battery installed and finally opted for the wlcrs/huawei_solar package. However, if you'd like to improve your plugin with Emma, I'd be happy to share my Northbound access with you, would you?

**Comment by tijsverkoyen** [comment]
@alexdess if you are not using this integration I won't invest the time.
Thanks anyway.

**Comment by tijsverkoyen** [comment]
I think https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/188 is related.
