### ISSUE TITLE
Smartguard Power Meter Sensors missing - no metering

### ISSUE THREAD

**Issue by Skymashi** [tijsverkoyen/HomeAssistant-FusionSolar#188]
**Describe the bug**
Sensors missing when Huawei Smartguard is used
Missing sensors:
sensor.xxx_reverse_active_energy
sensor.xxx_active_energy_forward_active_energy

** Debug information **
When Smartguard is installed the normal Power Meter is removed as the Smartguard has built-in EMMA and Power Meter

* Are you using the latest version of Home Assistant?
yes
* Are you using the latest version of this integration?
yes
* Have you looked into the closed issues and did not find a similar issue.
yes
* Are you using Kiosk or Northbound / OpenAPI mode?
API

* Have you checked the logs for any info? 
No info found as the integration seems not to detect/add the different sensors

**To Reproduce**
1. Go to Energy configuration
2. Try to set the grid consumption

**Expected behavior**
able to chose sensors for power metering and export

**Comment by tijsverkoyen** [comment]
@Skymashi I don't own a Huawei Smartguard. If you are willing to share your credentials (ha-fusionsolar [at] Verkoyen [dot] eu) I can see what the API exposes.

**Comment by tijsverkoyen** [comment]
@Skymashi from my first findings the Northbound API does not support pulling `getDevRealKpi` for devTypeId 2307023070: EMMA or devTypeId: 23071 SmartGuard.

That is why the devices are created but don't have any entities.
<img width="1020" alt="fa1" src="https://github.com/user-attachments/assets/82099170-6aed-4e82-9d5f-cdcf731b481b">

So it is not possible to monitor the grid consumption and return to grid. Feel free to contact the Huawei Fusion Solar helpdesk and ask them if it is possible to get this data through the API, and if so: how.
