### ISSUE TITLE
OAuth2Error: The device code has expired.

### ISSUE THREAD

**Issue by VinnieBaz** [tijsverkoyen/HomeAssistant-FusionSolar#189]
**Describe the bug**
Losing connection to my plant 

** Debug information **
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant? HAOS 2024.9.1
* Are you using the latest version of this integration? 3.0.5
* Have you looked into the closed issues and did not find a similar issue. I have looked and found similar issues but still not the same.
* Are you using Kiosk or Northbound / OpenAPI mode? North/Open API
* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. See [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#how-can-i-verify-my-northbound-api--openapi-credentials) Not via the method mentioned, but the credentials are working when i add the hub.
* Have you checked the logs for any info? 

Debug info:

OAuth2Error: The device code has expired.
    at OAuth2.<anonymous> (file:///rootfs/node_modules/youtubei.js/dist/src/core/OAuth2.js:96:99)
    at Generator.next (<anonymous>)
    at fulfilled (/rootfs/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  info: { error: 'expired_token', error_description: 'Expired user code' },
  date: 2024-09-10T11:44:27.134Z,
  version: '10.0.0'

**Comment by tijsverkoyen** [comment]
I don’t think this is an error from this integration. As it does not use OAuth
Nor does it use anything from node_modules

I suggest you remove the integration and check if the error is still present.

**Comment by VinnieBaz** [comment]
I´ll try that then! Thank you,

**Comment by tijsverkoyen** [comment]
@VinnieBaz did you have the time to check? Can I close this issue?

**Comment by VinnieBaz** [comment]
Apologies, given your reply I thought we considered the issue resolved :) I removed the integration yesterday and added it again but it kept losing contact.. However I realized that I have started an old instance of HA that I'm using to pull some configuration from, I'm wondering if it could cause problems, that it's two different instances connecting to the same API with the same account? I just removed FusionSolar from the old instance and am in the process of reinstalling it on the new one..

With all that said you can go ahead and close the issue :)
