### ISSUE TITLE
power_sensor_active_energy_forward_active_energy showing total instead of per day

### ISSUE THREAD

**Issue by ward0** [tijsverkoyen/HomeAssistant-FusionSolar#193]
**Describe the bug**

The Entitie: 'sensor.power_sensor_active_energy_forward_active_energy' shows the total instead of per day.

![image](https://github.com/user-attachments/assets/75ed893b-c6bb-4d90-afe5-425556c44395)

When I try to work with this sensor in ApexChart I get the wrong information:
![image](https://github.com/user-attachments/assets/b7851bc1-5ec4-4ac2-85bb-169aeb11de05)

When I go into the HA energy default dashboard I get the correct data for today:
![image](https://github.com/user-attachments/assets/f2508762-401f-428b-9200-cbe523d9c088)

My question is, does the HA dashboard automatically do a calculation to calculate today?

** Debug information **
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant?: Yes
* Are you using the latest version of this integration? : Yes
* Have you looked into the closed issues and did not find a similar issue.  Yes
* Are you using Kiosk or Northbound / OpenAPI mode? :  OpenAPI
* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. See [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#how-can-i-verify-mynorthbound-api--openapi-credentials): credentials are valid
* Have you checked the logs for any info? : yes

**Comment by tijsverkoyen** [comment]
This is expected. `xxx_active_energy_forward_active_energy` is the **total** return to grid.

**Comment by ward0** [comment]
I created a helper to get the kWh per day.
