### ISSUE TITLE
Overview is not available via Kiosk mode.

### ISSUE THREAD

**Issue by mariushosting** [tijsverkoyen/HomeAssistant-FusionSolar#199]
Unable to view the Power Chart and Overview data via Kiosk URL.
We are able to view only 5 data from Kiosk not all 8 datas.

**Comment by tijsverkoyen** [comment]
Can you explain which data is missing exactly.
Note that Kiosk exposes less data then API

**Comment by annopkomol** [comment]
<img width="352" alt="image" src="https://github.com/user-attachments/assets/2fb79709-7cac-4e68-96e4-553339f36358">

I can see only 5 entities from Kiosk mode, so I try to access the URL directly from the browser and there're only 5 items there. 
Not sure if that's the limitation of Kiosk mode?. @tijsverkoyen 
<img width="1655" alt="image" src="https://github.com/user-attachments/assets/1446c4e3-8687-4aff-a3ec-f7d44e91c576">

**Comment by tijsverkoyen** [comment]
@annopkomol What data are you missing?

**Comment by annopkomol** [comment]
@tijsverkoyen 
`sensor.xxx_reverse_active_energy` for grid consumption.
`sensor.xxx_active_energy_forward_active_energy` for return to grid

**Comment by tijsverkoyen** [comment]
@annopkomol these are not exposed when you are using the kiosk mode.
