### ISSUE TITLE
Configuration flow does not appear

### ISSUE THREAD

**Issue by michelmalle** [tijsverkoyen/HomeAssistant-FusionSolar#20]
After installing the integration through HACS the "config flow" does not appear. I did test it on two instances but no setup flow appeared. Is there a way to do this by config file or to trigger the configuration again?

**Env:**
Home Assistant 2022.11.5
Frontend 20221108.0 - latest

..running as a container.

HA log says nothing special:

_2022-12-03 21:29:33.273 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration fusion_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant_

Fusion Solar integration appears in HACS:
<img width="1613" alt="image" src="https://user-images.githubusercontent.com/26696704/205461073-6c9f5a9e-91a1-4f6e-a7ed-004347d4e0dc.png">

I hope you can help me out. 

Best,
Michel

**Comment by tijsverkoyen** [comment]
Did you upgrade from https://github.com/tijsverkoyen/Home-Assistant-FusionSolar-Kiosk?

**Comment by mingwenz** [comment]
Same issue!

**Comment by mingwenz** [comment]
> Did you upgrade from https://github.com/tijsverkoyen/Home-Assistant-FusionSolar-Kiosk?

I have the same problem and I did not upgrade from "Home-Assistant-FusionSolar-Kiosk", but I downloaded directly the https://github.com/tijsverkoyen/HomeAssistant-FusionSolar repository

**Comment by Wintherman** [comment]
Hi
I get the same problem with no configuration start when I start up the integration in HA.
When I download the v2.2.0 nothing happens when I restart HA. It does only open up the ReadMe file.
And I try to find out how to download to HA from [GitHub](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar)
but I can not find any kind of Download or HA integration buttom there.
I am a total beginner of HA but I have Fusion-Solar inverter SUN2000-6KTL and plan to install a battery pack of 15 kWh and control the charging and de-charging based on the NordPool integration giving me the hour prices.

**Comment by tijsverkoyen** [comment]
I still can't reproduce this issue. Can you increase log lever for Home Assistant and see if an error/warning/... pops up?

**Comment by attaxia** [comment]
Hi @tijsverkoyen ,

I'm running into the same issue. I'm running a clean install (installed 3 days ago) of Home Assistant OS on a Raspberry Pi 4.

I have no idea how it's supposed to look, but I attached a screen recording to show what I'm seeing. I'm hoping that helps. Will also look into raising log level.

https://user-images.githubusercontent.com/4743303/210053019-e823c4a4-77a9-446c-a6b6-1463f4b6a627.mp4



In the meantime, is there a reference so I can configure it by editing the configuration.yaml?

**Comment by tijsverkoyen** [comment]
I don't know for sure, but HACS won't shown the config flow.
When you have added the integration (as you did) you need to add it in Home Assistant: Settings → Devices & Services → Add Integration → Search for FusionSolar. Then the config flow will pop up

**Comment by attaxia** [comment]
You are 100% right, this fixed it for me. I'm new to HACS so didn't realize I _also_ needed to add the integration a second time through the "normal" settings.

Thanks!

**Comment by Wintherman** [comment]
Superthanks. It helped me as well.
Now I know HACS integrations as visible in HA integrations after installation.
Now I start with Kiosk and when Huawei finaly will give me the token (waited 3 days now) for OpenAPI I will go for that.
And I learned how to work with the logging settings :-)

**Comment by tijsverkoyen** [comment]
👍 
HACS just manages non official integrations. I does not enable them.
Glad it works
