### ISSUE TITLE
Yield issue after Sunset with Battery

### ISSUE THREAD

**Issue by Elekesey** [tijsverkoyen/HomeAssistant-FusionSolar#200]
**Describe the bug**
I use the integration with Inverter and Battery. Unfortunately, Daily Yield seems to calculate Battery (and Inverter) consumption.  So, after sunset*, when Battery is delivering power, Daily Yield is decreasing and causes an error in the solar production graph of Home Assistant.

On FusionSolar web and app, we can see Yield decreased while Battery delivers current.

*Check this post : https://forums.moneysavingexpert.com/discussion/comment/80098608/#Comment_80098608

**Debug information**
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant? **Yes**
* Are you using the latest version of this integration? **Yes**
* Have you looked into the closed issues and did not find a similar issue. **Yes**
* Are you using Kiosk or Northbound / OpenAPI mode? **OpenAPI mode**
* If you are using Kiosk mode. Have you checked that the url is still valid? See [I am using the kiosk mode, but the data is not updating](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#i-am-using-the-kiosk-mode-but-the-data-is-not-updating)
* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. See [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#how-can-i-verify-my-northbound-api--openapi-credentials) **Still valid**
* Have you checked the logs for any info? **Yes**

**To Reproduce**
1. Go to 'Energy Dashboard'
2. See error on Solar Production graph

**Expected behavior**
As _sensor.xxx_total_current_day_energy_ is used as solar panel sensor, it should have another sensor that doesn't take count of Battery and Inverter consumption.

**Screenshots**
![Capture d'écran 2024-11-04 203843](https://github.com/user-attachments/assets/1e17e2e5-7330-4d5d-99da-f1de43e9e35c)
![Capture d'écran 2024-11-04 204908](https://github.com/user-attachments/assets/257342a3-bc61-4308-a88a-18867033ba3a)

**Comment by tijsverkoyen** [comment]
The integration does not do any calculations. It uses the data received from the Huawei Fusion Solar API.

**Comment by Elekesey** [comment]
If anyone else get stuck with this, solution seems be done at https://github.com/wlcrs/huawei_solar/wiki/Daily-Solar-Yield
