### ISSUE TITLE
Mancano alcune informazioni nell'integrazione del Kiosk

### ISSUE THREAD

**Issue by SimoneRullo** [tijsverkoyen/HomeAssistant-FusionSolar#201]
**Describe the bug**
Some information is missing in the Kiosk integration, including:

- power curve
- environmental benefits
- overview

** Debug information **
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant? YES
* Are you using the latest version of this integration? YES
* Have you looked into the closed issues and did not find a similar issue. YES
* Are you using Kiosk or Northbound / OpenAPI mode? KIOSK
* If you are using Kiosk mode. Have you checked that the url is still valid? See [I am using the kiosk mode, but the data is not updating](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#i-am-using-the-kiosk-mode-but-the-data-is-not-updating) YES, UPDATED A FEW MINUTES AGO
* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. See [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#how-can-i-verify-my-northbound-api--openapi-credentials)
* Have you checked the logs for any info? NO

**To Reproduce**

**Expected behavior**
I would have expected to see, in addition to the current, daily, monthly, annual and total performance data, also the 3 final pieces of information indicated in the kiosk summary (power curve, environmental benefits, overview)

**Screenshots**
![kiosk ](https://github.com/user-attachments/assets/79a77dd7-e561-4295-8ea4-0c85d1ebcd73)

**Comment by tijsverkoyen** [comment]
In Kiosk mode only a limited amount of entities is exposed. If you need more detailed data I think Northbound API method is the way to go.
