### ISSUE TITLE
After HA update warning about deprecated function

### ISSUE THREAD

**Issue by MaBeniu** [tijsverkoyen/HomeAssistant-FusionSolar#202]
Home assistant Core : 2024.11.1

Logger: homeassistant.core
Source: helpers/deprecation.py:222
First occurred: 9:27:56 AM (1 occurrences)
Last logged: 9:27:56 AM

Config was used from fusion_solar, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'fusion_solar' custom integration

**Comment by tijsverkoyen** [comment]
Will be fixed when https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/205 is merged an released.

**Comment by MaBeniu** [comment]
Very much appreciated!! Any ETA?
