### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\?'

### ISSUE THREAD

**Issue by ben-tsk** [tijsverkoyen/HomeAssistant-FusionSolar#207]
**Describe the bug**
I just noticed the warning after updating from [v3.0.5](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/releases/tag/v3.0.5) to [v3.0.6](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/releases/tag/v3.0.6)

Home Assistant Core Log:
```
2024-11-21 22:41:57.150 WARNING (ImportExecutor_0) [py.warnings] /config/custom_components/fusion_solar/fusion_solar/kiosk/kiosk.py:16: SyntaxWarning: invalid escape sequence '\?'
  id = re.search("\?kk=(.*)", self.url).group(1)
``` 

**Debug information**
* Are you using the latest version of Home Assistant? -> yes
* Are you using the latest version of this integration? -> yes
* Have you looked into the closed issues and did not find a similar issue. -> yes
* Are you using Kiosk or Northbound / OpenAPI mode? -> OpenAPI
* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. See [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#how-can-i-verify-my-northbound-api--openapi-credentials) -> yes, credentials still valid
* Have you checked the logs for any info? -> yes

**To Reproduce**
1. Restart Home Assistant

**Expected behavior**
No warning

**Comment by tijsverkoyen** [comment]
Which version of Home Assistant are you using?

**Comment by tijsverkoyen** [comment]
See https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/160 also, which describes the same problem. I suspect you are using an old version of Home Assistant or an old Python version.

**Comment by ben-tsk** [comment]
I actually got the warning only once after updating the integration from [v3.0.5](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/releases/tag/v3.0.5) to [v3.0.6](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/releases/tag/v3.0.6) and restarting HA afterwards. I dont get the warning anymore. 

The instance is a fresh install, idk if it was 2024.11.2 or 2024.11.3.

**Comment by MaBeniu** [comment]
Updated to the latest. 3.1.0
Still the same error on HA start up

'''
This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/fusion_solar/sensor.py:21
integration: Fusion Solar (documentation, issues)
First occurred: 6:30:14 PM (1 occurrences)
Last logged: 6:30:14 PM

/config/custom_components/fusion_solar/fusion_solar/kiosk/kiosk.py:16: SyntaxWarning: invalid escape sequence '\?' id = re.search("\?kk=(.*)", self.url).group(1)
'''

**Comment by ben-tsk** [comment]
Updated from [v3.0.6](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/releases/tag/v3.0.6) to [v3.1.0](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/releases/tag/v3.1.0)

Same warning on only the first restart after update: 
```
2024-11-24 17:39:57.796 WARNING (ImportExecutor_0) [py.warnings] /config/custom_components/fusion_solar/fusion_solar/kiosk/kiosk.py:16: SyntaxWarning: invalid escape sequence '\?'
  id = re.search("\?kk=(.*)", self.url).group(1)
```

**Comment by tijsverkoyen** [comment]
Check the python version that your installation is using

**Comment by MaBeniu** [comment]
Thanks a lot for fast response.
Sorry but I don't how to check, any tips? I use latest home assistant release

**Comment by ben-tsk** [comment]
> Check the python version that your installation is using

```
➜  ~ python --version
Python 3.12.3
```

**Comment by tijsverkoyen** [comment]
How do you run Home Assistant? Docker? Home Assistant OS?

**Comment by ben-tsk** [comment]
> How do you run Home Assistant? Docker? Home Assistant OS?

HA OS virtualized

**Comment by MaBeniu** [comment]
After few restarts, I don't get warning any more 🤷
