### ISSUE TITLE
Invalid Handler Specified 

### ISSUE THREAD

**Issue by emanueletocci** [tijsverkoyen/HomeAssistant-FusionSolar#215]
Hi, from the last update I'm not able to use the integration. No datas, as the title I always see that error when I try to add the integration...

`Invalid Handler Specified`.

![image](https://github.com/user-attachments/assets/93dee822-ebe3-4314-b5ac-bed3aee5d202)

Reading the log files I've found this entry:

`2024-12-19 15:57:21.288 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration fusion_solar: No module named 'homeassistant.core_config'`

Seeing commit history I see that `from homeassistant.core import HomeAssistant, Config` was turned into `from homeassistant.core import HomeAssistant
from homeassistant.core_config import Config` by  `Commit b704cb5`, "Merge pull request #205 from tijsverkoyen/202-Config-deprecation".

Bringing it back it seems to work properly:
![image](https://github.com/user-attachments/assets/2b4273bb-cf78-44cd-a508-b6174d301212)

**Comment by tijsverkoyen** [comment]
Which version of Home Assistant are you using?

**Comment by emanueletocci** [comment]
core 2024.9.3

**Comment by tijsverkoyen** [comment]
You should update Home Assistant. The current release is 2024.12
