### ISSUE TITLE
ACCESS_FREQUENCY_IS_TOO_HIGH

### ISSUE THREAD

**Issue by vipii** [tijsverkoyen/HomeAssistant-FusionSolar#25]
Hi,

I have setup the integration on my Home Assistant with my API Credentials I received from my installer.
With these credentials I can't login on https://region01eu5.fusionsolar.huawei.com/, but I can do posts / gets with the API with tools like postman. So they do actually work.

Also when I lookup the entities, the diagnostics are getting data from the account. Like battery device ID, all the optimisers, transformers etc etc... So the connection is working I am guessing? But the problem is that the sensors are not reading / getting any data. All the time I get the message "Not available". 

When I reboot the docker setup and watch the logs, I do see this message:

2022-12-13 21:00:29.970 ERROR (MainThread) [custom_components.fusion_solar.sensor] Unexpected error fetching FusionSolarOpenAPIDeviceRealKpi data: Retrieving the data failed with failCode: 401, message: Invalid access to current interface!

Any way how I can fix this?

**Comment by tijsverkoyen** [comment]
I suspect this is the same issue as in: https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/12 or https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/17

Can you check the response for: 
curl --location --request POST 'https://eu5.fusionsolar.huawei.com/thirdData/getDevList' \
--header 'XSRF-TOKEN: x-REDACTED' \
--header 'Content-Type: application/json' \
--data-raw '{
  "stationCodes": "XXX"
}'

If this is empty: you should contact Huawei support and ask them to link the correct plant to your OpenAPI credentials.
If not empty: I can debug it for you, but then I will need your OpenAPI credentials. You can send them to me at `fusion solar [at] Verkoyen.eu`

**Comment by vipii** [comment]
Hey Tijs, 

I got the StationCode, if you want you may Debug it for me.
Fusion-solar [at] or what is the email-adress?

I also sended you a message on Messenger (Facebook) might be in your to-accept chat list ;-) 
Easier to talk if you would like to accept that.

**Comment by tijsverkoyen** [comment]
fusionsolar[at]verkoyen.eu

**Comment by vipii** [comment]
I have send an email :-)

Thanks in advance!

**Comment by tijsverkoyen** [comment]
It seems to be a Rate Limiting issue. Where I access getDevRealKpi more then 1 per minute as there are multiple devices
I probably will need to rethink part of the code to resolve this issue, so this won't be a quick fix.

**Comment by vipii** [comment]
You want me to temp disable the addon in Home Assistant so it does not access the Kpi every 1 minute? 
Else you probably can't debug it because of my Home Assistant is blocking the API rate limit?

**Comment by tijsverkoyen** [comment]
That would be nice.

**Comment by vipii** [comment]
Done! Disabled the addon.

**Comment by tijsverkoyen** [comment]
@vipii The issue should be resolved as soon as you have installed [v2.2.0](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/releases/tag/v2.2.0)

There is something weird with your install, as you have a batter and power sensor in your plant, but these don't return any data.
