### ISSUE TITLE
Cannot find kiosk.. :(

### ISSUE THREAD

**Issue by s0len** [tijsverkoyen/HomeAssistant-FusionSolar#28]
Hi, I know this is not really an issue but I also dont know how to ask in a better way so here goes.

I can't find Kiosk.. Please help 

EDIT: Solved, my account was an installers and I just added another account which was solely an owner

**Comment by tijsverkoyen** [comment]
See https://forum.huawei.com/enterprise/en/settings-for-single-plant-sharing-kiosk-view-in-fusionsolar-7-server/thread/806217-100027
I think you are logged in as an installer?
