### ISSUE TITLE
Can't use battery power in Energy Dashboard

### ISSUE THREAD

**Issue by bonfa53** [tijsverkoyen/HomeAssistant-FusionSolar#31]
I have a plant with battery and I can see battery data in main dashboard, but can't use battery power in Home Assistant Energy dashboard. The entity is sensor.battery_charge_discharge_power.
I'm using the last version of integration with an OpenAPI account.

Dashboard battery data:
![image](https://user-images.githubusercontent.com/15247977/209802136-ccce8855-ab88-485e-8d29-172408454572.png)

When I try to add battery energy I can only select charging and discharging capacity, but not power

![image](https://user-images.githubusercontent.com/15247977/209802546-1c07f2c8-302b-4f3f-8471-240a23771bdd.png)

Home Assistant help suggests that entity is not defined correctly [https://www.home-assistant.io/more-info/statistics/](https://www.home-assistant.io/more-info/statistics/). I can guess from entity icons that the entities are defined in different way, maybe there is a way to change entity type to "energy" type.

Thank you for your work and your help

**Comment by tijsverkoyen** [comment]
I don't know for sure, but Home Assistants expects a value in kWh, but Charge/Discharge Power is reported in W
In my opinion "Energy coming out of the battery" is "Discharing capacity" but I don't know much about batteries.

**Comment by bonfa53** [comment]
Thank you for your reply, I'm waiting for some sunny days to check the correct entity for current energy

**Comment by tijsverkoyen** [comment]
Ok, I will close the issue at this point. You can reopen it if you think there is still an issue.
