### ISSUE TITLE
Grid Data & load data are missing

### ISSUE THREAD

**Issue by Liaven** [tijsverkoyen/HomeAssistant-FusionSolar#32]
Hi. I'm using kiosk and only get 1 device with 5 sensors (realtime power, and 4 totals) It's possible to obtain load and grid data?

**Comment by mkosmida2** [comment]
if they are visible in the kiosk i would say yes
copy the link you got from FusionSolar and open in a browser

**Comment by tijsverkoyen** [comment]
@Liaven I don't have a batter and such, so I don't see a load/grid data in my kiosk.
Are you willing to share your kiosk-url? You can share it here or send it to `fusionsolar [at] verkoyen.eu`. With that I can check if the data is present in the API call.
Just a note: I'm a bit busy at the moment, so I don't promise anything.

**Comment by tomazzive** [comment]
Hi, I have the same "issue". Only 5 sensors. While there is very important information in FusionSolar, for example: battery load, battery charge, battery discharge. When I open the link, I'm limited with realtime power and 4 totals. So FusionSolar is not passing a lot of information. Would I get more information if using the Open API?

**Comment by tijsverkoyen** [comment]
With the OpenAPI account you will have a lot more info.
But if you are willing to share your kiosk url with me, I can look if there is more data available.

**Comment by tomazzive** [comment]
I sent it to your email!

**Comment by tijsverkoyen** [comment]
I don't see that load, charge, ... info in the kiosk. So I can't make it available.
I think the best option would be to use the OpenAPI integration

**Comment by tijsverkoyen** [comment]
@tomazzive any update on this? Please reopen the issue if you see more then me.
