### ISSUE TITLE
Using OpenAPI, Battery and Power Sensor entities are set to Unknown state.

### ISSUE THREAD

**Issue by Karakth** [tijsverkoyen/HomeAssistant-FusionSolar#34]
Using OpenAPI, 153 entities are retrieved.
I have 2 devices which are returning Unknown as entity states: The Battery and the Power Sensor.
The other devices (inverter, dongle, plant) all manage to populate their entities with values.

Any help would be appreciated.

**Comment by tijsverkoyen** [comment]
Is there any info in the logs?

**Comment by Karakth** [comment]
Just realized I'm also getting the ACCESS_FREQUENCY_TOO_HIGH error. Running Ver 2.2.0

**Comment by tijsverkoyen** [comment]
See https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/29
