### ISSUE TITLE
Unknown data almost everywhere

### ISSUE THREAD

**Issue by agm15** [tijsverkoyen/HomeAssistant-FusionSolar#36]
Hello, i will try this as best as I can.

I got the OpenAPI credentials, installed the plugin, put the information in and I can see 3 devices listed:

- My name - Station
- SerialNumber - Residential Inverter
- Power Sensor - Power Sensor

If I click in the device Station, I can see information such as Total Current Day Energy with values that matches the app, so that one works good.

If I click in any of the other devices, lets say the inversor, all variables are set as unknown (Active power, GridAB voltage.....)

I already installed the plugin and uninstalled it,  also waitted a couple of hours before opening a ticket to see if it was because it was still fetching information or something like that but its still happening.

I enabled the logs and I have this information:

`FusionSolarOpenAPIDeviceRealKpiType Skipped call due to rate limiting. Wait for 189.0 seconds. 0/2
FusionSolarOpenAPIDeviceRealKpiType Skipped call due to rate limiting. Wait for 126.0 seconds. 1/2
FusionSolarOpenAPIDeviceRealKpiType Skipped call due to rate limiting. Wait for 63.0 seconds. 2/2`

I've checked the closed tickets and seems somewhat similar to issue #29 but i don't know.

Is there anything I can do, or that I am doing wrong?

I would apreciate the help, and also, thanks a lot for creating this addon!

**Comment by tijsverkoyen** [comment]
First of all: the warning in the logs is just so you know you have hit the rate limiting.
Are you 100% sure there is no other integration of anything else using your credentials?
Feel free to send your OpenAPI credentials to me (`fusionsolar [at] Verkoyen.eu`)

**Comment by agm15** [comment]
Yeah, im sure, the credentials were sent to me this morning by the company that did the installation of the pannels and I've only requested it for using it on your plugin.

I've just emailed the info, thanks in advance!!

**Comment by tijsverkoyen** [comment]
@agm15 the problem is that there is no data returned for your residential inverter.

In essence the following call:
````bash
curl --location --request POST 'https://eu5.fusionsolar.huawei.com/thirdData/getDevRealKpi' \
--header 'XSRF-TOKEN: x-REDACTED' \
--header 'Content-Type: application/json' \
--data-raw '{
  "devIds": "XXXX",
  "devTypeId": "38"
}'
````

Return the following data:

````json
{
    "data": [
        {
            "devId": XXXX,
            "dataItemMap": {}
        }
    ],
    "failCode": 0,
    "message": null,
    "params": {
        "currentTime": 1673365478224,
        "devIds": "XXXX",
        "devTypeId": 38
    },
    "success": true
}
````

Where it should look like:

````json
{
    "data": [
        {
            "devId": XXX,
            "dataItemMap": {
                "pv1_u": 0.0,
                "pv2_u": 0.0,
                "pv3_u": 0.0,
                "pv4_u": 0.0,
                "pv5_u": 0.0,
                "pv6_u": 0.0,
                "power_factor": 0.0,
                "pv7_u": 0.0,
                "pv8_u": 0.0,
                "inverter_state": 40960.0,
                "open_time": 1673336086000,
                "a_i": 0.0,
                "total_cap": 6177.93,
                "c_i": 0.0,
                "b_i": 0.0,
                "mppt_3_cap": 0.0,
                "a_u": 0.0,
                "reactive_power": 0.0,
                "c_u": 0.0,
                "temperature": 24.9,
                "b_u": 0.0,
                "bc_u": 0.0,
                "elec_freq": 0.0,
                "mppt_4_cap": 0.0,
                "efficiency": 0.0,
                "day_cap": 0.72,
                "mppt_power": 0.0,
                "run_state": 1,
                "close_time": 1673364384000,
                "mppt_1_cap": 6376.98,
                "pv1_i": 0.0,
                "pv2_i": 0.0,
                "pv3_i": 0.0,
                "pv4_i": 0.0,
                "mppt_2_cap": 0.0,
                "active_power": 0.0,
                "pv5_i": 0.0,
                "ca_u": 0.0,
                "ab_u": 0.0,
                "pv6_i": 0.0,
                "pv7_i": 0.0,
                "pv8_i": 0.0
            }
        }
    ],
    "failCode": 0,
    "message": null,
    "params": {
        "currentTime": 1673365696381,
        "devIds": "XXXX",
        "devTypeId": 38
    },
    "success": true
}
````

I don't have installer access, but from what I found in docs and screenshots I think you should ask your installer to enable "Real-time plant data"

<img width="1175" alt="Cursor_and_2022FSV8001_Create_API_account_on_FusionSolar_Server__only_Company_Admin____pdf" src="https://user-images.githubusercontent.com/250042/211599267-9bc6e4f7-39d0-44a1-927d-3049a7748045.png">

**Comment by agm15** [comment]
Thank you so much for the answer, I've just emailed the company asking them
to check the permissions they've given me, hopefully it will be that stupid
thing!

Thanks a lot for taking your time responding me, I will make sure to update
the issue once I have it all working!!!

**Comment by agm15** [comment]
I've talked to the company and they are assuring me that all the checks for the permisions are enabled and that I should have access to everything.

**Comment by tijsverkoyen** [comment]
I rechecked, and the data is still empty. There is not much I can do at this point.
I think it would be best to contact Fusion Solar Support `eu_inverter_support@huawei.com` and explain them that there is no data returned for your residential inverter (1000000034152004) when calling the `/thirdData/getDevRealKpi` endpoint.

**Comment by agm15** [comment]
Hello,

You can close the issue, I've submitted everything to huawei support, pictures of the permissions and everything and they have fixed the issue, i'm now receiving information correctly!

Thanks a lot!

**Comment by tijsverkoyen** [comment]
Thx for the update!
Glad it has been resolved
