### ISSUE TITLE
Real Time Power value in Kiosk mode not updating after version 2.3.0 upgrade

### ISSUE THREAD

**Issue by mingwenz** [tijsverkoyen/HomeAssistant-FusionSolar#37]
The Real Time Power entity is not updating its value (every 30 minutes) in Kiosk mode after the upgrade to version 2.3.0.
The new entity value is taken only after a system restart.
I am currently running the fusion solar integration(version 2.3.0) on the home assistant core version 2023.1.0. The previous integration version was working perfectly.
The other fusion solar entities (total_current_day_energy...) update their values correctly.
Unfortunately the system logs do not show any relevant message.

**Comment by tijsverkoyen** [comment]
Thx! 
Fixed in v2.3.1: https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/releases/tag/v2.3.1

**Comment by mingwenz** [comment]
Working perfectly now! Thank you!
