### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Picorama** [tijsverkoyen/HomeAssistant-FusionSolar#39]
Dont know how to use this. I have Fusion solar in my browser, but cant see anything like the KIOSK thing u refere to.
Installation guide could be better.

**Comment by tijsverkoyen** [comment]
@Picorama feel free to help me with improving the documentation.
I have added a FAQ section with information on how to retrieve the kiosk url: https://github.com/tijsverkoyen/HomeAssistant-FusionSolar#where-can-i-find-the-kiosk-url
