### ISSUE TITLE
no kiosk ??

### ISSUE THREAD

**Issue by Picorama** [tijsverkoyen/HomeAssistant-FusionSolar#40]
?? i dont know where else to ask but in here.
![Skærmbillede 2023-01-13 152706](https://user-images.githubusercontent.com/98780926/212344915-b2dc39ed-be2f-42e8-bd94-4916210fdb43.jpg)

**Comment by tijsverkoyen** [comment]
@Picorama See the FAQ, if you are not seeing the Kiosk button you are probably logged in with an installer account. If not: contact Fusion Solar support or your installer.
