### ISSUE TITLE
Cannot import name 'UnitOfElectricCurrent'

### ISSUE THREAD

**Issue by lubosramo** [tijsverkoyen/HomeAssistant-FusionSolar#41]
Please could you help me? I added Fusion Solar integration (via HACS), using Kiosk mode, restarted HA, but I am getting following error:

```
Logger: homeassistant.setup
Source: setup.py:338
First occurred: 6:44:03 PM (1 occurrences)
Last logged: 6:44:03 PM

Unable to prepare setup for platform fusion_solar.sensor: Platform not found (cannot import name 'UnitOfElectricCurrent' from 'homeassistant.const' (/usr/lib/python3.10/site-packages/homeassistant/const.py)).
```

Thank you very much.

**Comment by tijsverkoyen** [comment]
Which version of Home Assistant are you using? Can you check if you have the latest, which should be 2023.01

**Comment by lubosramo** [comment]
I see this in Settings/About section:
Home Assistant 2022.12.6
Frontend 20221213.0 - latest

And this in Settings/Updates:
No updates available

Probably I must do update via console, actually I wanted to avoid this as I am newby :-)

**Comment by tijsverkoyen** [comment]
Updating Home Assistant depends on the way you have it installed.
Please close the issue if updating Home Assistant resolved the issue.

**Comment by lubosramo** [comment]
HA update resolved the issue, thanks.
