### ISSUE TITLE
Using API doesn’t work properly

### ISSUE THREAD

**Issue by GeeGee-be** [tijsverkoyen/HomeAssistant-FusionSolar#42]
After many mails with Huawei support to have all data available through API, still I only see 10 entities. Huawei claims all data has been enabled to be read. Nevertheless, I don’t get the data to see that I would like to see (for example my battery level).

**Comment by tijsverkoyen** [comment]
If you mail (`fusionsolar [at] Verkoyen.eu`) me your OpenAPi credentials I will try to debug.

**Comment by GeeGee-be** [comment]
Dag Tijs,

Hier mijn credentials:
Gebruiker: Geladi_te_Diepenbeek
Paswoord: Huawei2022

Mvg
Gunter

Op ma 16 jan. 2023 om 08:59 schreef Tijs Verkoyen ***@***.***>

**Comment by GeeGee-be** [comment]
Dag Tijs,

Bedankt voor deze test en feedback.
Probleem is dat ik via mijn leverancier altijd bij Wattkraft Benelux
terechtkom en niet direct bij Fusion Solar support. Fusion solar verwijst
le door naar Wattkraft en die zijn niet zo mee met de zaak heb in de indruk.

Ik probeer met je info nogmaals.

Mvg
Gunter


Op ma 16 jan. 2023 om 13:27 schreef Tijs Verkoyen ***@***.***>

**Comment by PetaPi314** [comment]
Ik heb momenteel hetzelfde probleem met dezelfde foutmelding.
Ik dacht ook dat het lag aan mijn leverancier, maar na een telefoontje bleken ze wel degelijk mee te zijn met het probleem (omdat ze regelmatig aansluitingen testen en regelen voor energieID).
Vermoedelijk zijn ze bij Huawei vergeten enkele vinkjes te zetten. Probleem is dat de installateur telkens een nieuwe aanvraag moet indienen.

Jammer dat het Huawei systeem zo gesloten is en je als koper steeds afhankelijk bent van je installateur om aan je gegevens te kunnen.

**Comment by tijsverkoyen** [comment]
In my expierence eu_inverter_support@huawei.com is very responsive and also helps to explain what the installer needs to do exactly.

**Comment by tijsverkoyen** [comment]
@GeeGee-be @PetaPi314 was this resolved? If not: please reopen the issue.

**Comment by GeeGee-be** [comment]
@tijsverkoyen after a feedback from Wattkraft that they did a last attempt to enable all they could, I did remove and add the integration again. At that point 8 could see more devices and about 100 entities. So I see all parameters now. Issue solved. Thx!
