### ISSUE TITLE
Realtime not displayed

### ISSUE THREAD

**Issue by giuseppe91** [tijsverkoyen/HomeAssistant-FusionSolar#44]
I have integration with kiosk and works properly, but only entity “real time power” don’t be in energetic dashboard.
I’ve tried to create a template that read reltimePower data but it’s not work

template code:

template:
- sensor:
  - name: power_solar
    #state: "{{ (states(‘sensor.my_realtime_power')|float)}}"
    state: "25"
    unit_of_measurement: kWh  
    device_class: energy
    state_class: measurement
    last_reset: '1970-01-01T00:00:00+00:00'
    unique_id: power_solar

This template can be added on dashboard energy but display 0 value

**Comment by tijsverkoyen** [comment]
Realtime power is expressed in kW, not in kWh.
The Energy Dashboard expects a value in kWh, so you can't use Realtime power
