### ISSUE TITLE
Wrong unit of measurement for "Meter realtime power"

### ISSUE THREAD

**Issue by GiorgioUghini** [tijsverkoyen/HomeAssistant-FusionSolar#47]
Hello and thanks, really thanks, for your hard work.
I would like to inform you that the unit of measurement of my meter is wrong in HA. Is this something that can be corrected with a PR or it's a Huawei issue?
I'm using OpenAPI integration.
Thank you.
Screenshot attached.

![Huawei portal](https://user-images.githubusercontent.com/23707134/215569646-bea091f4-be48-4648-bf9b-4cb9f6fae80b.png)
![Home Assistant](https://user-images.githubusercontent.com/23707134/215569843-86a3fec0-4c5e-4764-8a25-efb45479ab4c.png)

Thank you again, I do really appreciate your work.
Giorgio

**Comment by tijsverkoyen** [comment]
Is this a Power Sensor
If so: are you 100% sure your are on the latest version? As this should be fixed in https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/commit/87c9b627f9a2c5a98d36292ccf955714cd755120

**Comment by GiorgioUghini** [comment]
I run FusionSolar 2.3.2, already rebooted HA instance during installation.

Is this a power sensor? I don't know honestly.
It's dev name should be "Meter-1", with devTypeId = 47.

This is the answer to getDevRealKpi:
`{"data":[{"devId":"REMOVED","dataItemMap":{"active_cap":56.11,"meter_status":1.0,"meter_i":-1.48,"reverse_active_cap":1454.08,"power_factor":-0.3,"reactive_power":300.0,"active_power":-3.0,"run_state":1,"meter_u":234.1,"grid_frequency":49.97}}],"failCode":0,"message":null,"params":{"currentTime":1675183524978,"devIds":"REMOVED","devTypeId":47},"success":true}`

**Comment by tijsverkoyen** [comment]
I don't see any reason why this is reported in kW.

devTypeId 47 are Power Sensors. The Active Power entity is created as a `FusionSolarRealtimeDeviceDataPowerInWattSensor` ([here](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/custom_components/fusion_solar/sensor.py#L535)). 
This Sensor has its `unit_of_measurement` set as W ([here](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/custom_components/fusion_solar/fusion_solar/realtime_device_data_sensor.py#L210))

I personally don't have a power sensor, so it is not easy to debug. But I have tested it with a plant with a Power Sensor, and as you can see in the screenshot below, the Active Power is reported in W.

<img width="557" alt="active_power" src="https://user-images.githubusercontent.com/250042/215847490-935412fe-7133-41ab-83ed-7f7cd2c443e9.png">

I find it strange that the name of the sensor is `Realtime Power`. Is this something you renamed it to?

**Comment by GiorgioUghini** [comment]
Based on your screenshot, I identified the correct sensor to be used, which should be "active power", that is correctly expressed in Watt.
Note the attached screenshot, I have also another sensor, different from this one, called "realtime power" that is wrongly expressed in kW.
But at least the two sensor report the same data so I will just switch to the active power one.
![Screenshot_2023-01-31-21-44-45-96_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/23707134/215879177-49b58de3-75ba-4b1a-9c94-c94086d80e35.jpg)

If you want, I can provide some logs, just tell me what you need, I am unfortunately not very familiar with HA / HACS coding.

Thank you

**Comment by GiorgioUghini** [comment]
Maybe here at line 169? Just guessing...
https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/e1e654a34b74c71cd59b46d5f825b3d70232c320/custom_components/fusion_solar/sensor.py#L169
