### ISSUE TITLE
Datapoints overflow ;)

### ISSUE THREAD

**Issue by zeputt** [tijsverkoyen/HomeAssistant-FusionSolar#49]
Hi,
Just got this working through the API connection.
It works very well, perhaps too good...

Is there a way to reduce the number of datapoints?
For instance I get from "PV1 input current" to "PV9 input current" with subs on PV1 and 2 (PV10 to PV19)

But I have just two strings on inverter-1 and one string on inverter-2.

![image](https://user-images.githubusercontent.com/9121429/216055878-af14ea9e-a45e-42c7-acca-904685c8b547.png)

**Comment by tijsverkoyen** [comment]
I don't get it. In Home Assistant you can decide which entities to show in a dashboard.

**Comment by tijsverkoyen** [comment]
@zeputt I assume you have added the full widget to your dashboard? If so: you can edit the dashboard and remove the items you don't want to see.

Feel free to reopen the issue if you think this is a problem within the integration. But at this point the integration just exposes the data that is coming from the Huawei Fusion Solar API.

**Comment by zeputt** [comment]
Sorry for not coming back sooner ;)
I know that you can select what to show and I only use the datapoints that makes sense in Node-Red and don't really use them in the UI.

My thought was if it's useful to be able to supress the datapoints that's not useful to you in order to mitigate this:

> This error originated from a custom integration.
> 
> Logger: custom_components.fusion_solar.sensor
> Source: custom_components/fusion_solar/fusion_solar/openapi/openapi_api.py:158
> Integration: Fusion Solar (documentation, issues)
> First occurred: February 7, 2023 at 14:29:36 (89 occurrences)
> Last logged: 08:41:50
> 
> Unexpected error fetching FusionSolarOpenAPIStationYearKpi data: Access frequency to high. failCode: 407, message: ACCESS_FREQUENCY_IS_TOO_HIGH
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
>     self.data = await self._async_update_data()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
>     return await self.update_method()
>   File "/config/custom_components/fusion_solar/sensor.py", line 655, in async_update_station_year_kpi_data
>     response = await hass.async_add_executor_job(api.get_kpi_station_year, station_codes)
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/fusion_solar/fusion_solar/openapi/openapi_api.py", line 92, in get_kpi_station_year
>     response = self._do_call(url, json)
>   File "/config/custom_components/fusion_solar/fusion_solar/openapi/openapi_api.py", line 158, in _do_call
>     raise FusionSolarOpenApiAccessFrequencyTooHighError(
> custom_components.fusion_solar.fusion_solar.openapi.openapi_api.FusionSolarOpenApiAccessFrequencyTooHighError: Access frequency to high. failCode: 407, message: ACCESS_FREQUENCY_IS_TOO_HIGH

I'm aware that it's depending on the way that the call is written but this was the reason way I raised the issue :)

**Comment by tijsverkoyen** [comment]
Hmm, would be a good idea. 
But I don't see a good way to implement this in the interface. Maybe something in the config flow that grabs all devices and let you select which ones to include. Will need to think about this. For probably not something that will be included very soon.

**Comment by catalinbordan** [comment]
Hi,
Could be a solution to disable the sensors from HA? Maybe would not be pulled by integration?
![image](https://user-images.githubusercontent.com/52258507/218685095-eb95ee18-863c-43aa-b60a-8aea683f471a.png)

**Comment by tijsverkoyen** [comment]
@catalinbordan thx for the insight.
@zeputt the `ACCESS_FREQUENCY_IS_TOO_HIGH` is not related to the entities. The call updates multiple entities if it receives data. The call is per device type, so the call also handles multiple devices at once.

I have created a [Pull Request](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/65) that takes the disabled devices into account. This will not request the information for the disabled devices.
