### ISSUE TITLE
Api configuration

### ISSUE THREAD

**Issue by eternum79** [tijsverkoyen/HomeAssistant-FusionSolar#5]
I installed the integration and accessed with the API credentials but no "solar" entity was created. Do I have to do anything else for correct operation? Before I used the Kiosk version and it worked well. Thanks

**Comment by tijsverkoyen** [comment]
On the integrations screen, are there any devices/entities listed for the integration?

**Comment by eternum79** [comment]
> On the integrations screen, are there any devices/entities listed for the integration?

With Kiosk, yes. Not with api

**Comment by tijsverkoyen** [comment]
Are there any errors in the logs?
Could you tell me which inverter you have?
Are you willing to share your OpenAPI credentials with me, so I can debug? If so: mail them to me fusionsolar [at] verkoyen.eu.

**Comment by eternum79** [comment]
> Are there any errors in the logs? Could you tell me which inverter you have? Are you willing to share your OpenAPI credentials with me, so I can debug? If so: mail them to me fusionsolar [at] verkoyen.eu.

Sure, but i don't find your email

**Comment by eternum79** [comment]
I have an Installer account, can this be the problem?

**Comment by eternum79** [comment]
They have released my API credentials and I can log in with Postman. I send you email.

**Comment by tijsverkoyen** [comment]
I tried to debug with your credentials but it seems like there are no stations linked to your account.

```bash
curl --location --request POST 'https://eu5.fusionsolar.huawei.com/thirdData/getStationList' \
--header 'XSRF-TOKEN: XXXXXXXXXXXXXXX' \
--header 'Content-Type: application/json' \
--data-raw '{}'
```

The response is:
```json
{
  "data":[],
  "failCode":0,
  "message":null,
  "params":{
    "currentTime":1667996616084
  },
  "success":true
}
```    
As you can see the data array is empty, where there are stations expected.
In the next release an error will be thrown when there are no stations.

You should contact FusionSolar and ask them why there are no stations/plants returned.
