### ISSUE TITLE
Energy Dashboard configuration

### ISSUE THREAD

**Issue by GiorgioUghini** [tijsverkoyen/HomeAssistant-FusionSolar#51]
Hello all,
I was seeking some help regarding the energy dashboard configuration upon which I'm struggling a few days now.

### Hardware setup
My system include:
- One inverter, linked to two strings
- One meter, measuring current incoming and outgoing from the grid
- One battery, storing energy not immediately auto-consumed

### Software setup
In the Energy dashboard, I put (json slightly edited for brevity):
`{
  "stat_energy_from_grid": "sensor.meter_1_reverse_active_energy",
  "stat_energy_to_grid": "sensor.meter_1_active_energy_forward_active_energy",
  "stat_energy_from_solar": [
    "sensor.inverter_1_mppt_1_dc_total_yield",
    "sensor.inverter_1_mppt_2_dc_total_yield"
  ],
  "stat_energy_from_battery": "sensor.battery_1_discharging_capacity",
  "stat_energy_to_battery": "sensor.battery_1_charging_capacity"
}`

Everything works well with this settings, as I do not compute energy twice, a thing that would happen using the inverter power into the `stat_energy_from_solar` field....

### Issue
In the energy dashboard, I am using several statistics which are total, and the battery statistics that go to zero each day at midnight.
When I first added HomeAssistant-FusionSolar integration, HA use the first datapoint value as zero-point, meaning that each midnight I get a drop in the statistics, and during the day, the battery in the energy dashboard is meaningless...
![image](https://user-images.githubusercontent.com/23707134/216094930-6ec89721-c0ea-4506-af12-55eb1de1016c.png)

See also:
![image](https://user-images.githubusercontent.com/23707134/216098918-11966366-27e4-4072-98f5-84193ae5fdec.png)

Similar to: https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/18

Anyone has some advice on how to configure it?
Thank you

**Comment by GiorgioUghini** [comment]
Every midnight, while other statistics resets to zero (in the frontend, in the backend they are still counting energy), the two battery statistics reset to negative values (in the  frontend, in the backend they are reset to zero as they are daily stats).
![image](https://user-images.githubusercontent.com/23707134/216200101-43df8f17-1e87-42b1-94cd-07d5627e7151.png)

In HA documentation they say that they keep the initial value when the statistic is added, as zero-point... Don't know if this may be relevant?

**Comment by tijsverkoyen** [comment]
I think I will first need to read up on the documentation.
I don't think the Huawei Fusion Solar API exposes when the data is reset, for probably I will need to recalculate of take the current time or, ...

I don't have much time the coming weeks as I'm busy with other projects. So don't expect a change very soon.
Feel free to create a pull request yourself.

**Comment by GiorgioUghini** [comment]
Actually, Home Assistant recognize the "last reset" by looking if a "total increasing" sensor goes to zero. At the end the logic is clear: the sensor starts from zero, it is total and it is INCREASING, so it goes to (say) 20kWh, and if this sensor drops to 0, well that's a reset. HA is intelligent enough for this.
Problem is that there's something in the initialization phase that set the so-called "zero-value" of the sensor to the value that it has in that moment. In this way, when it resets, it goes back to the zero-value (so if you setup this integration at 4PM when you already produced 15kWh, every middnight, the dashboard will display -15kWh).
I need to evaluate a possible solution for this too. 
There's no hurry, your work is already excellent as is. Just putting the issue here if anyone would like to contribute. I will, as soon as I manage a possible workaround for this.

**Comment by GiorgioUghini** [comment]
Progress so far:
1. Battery discharge capacity and Battery charge capacity are set to total, while they can set to total_increasing. See attached image. If sensor are kept total (without increasing) we should put in place routines to set last_reset based on drops to 0.
![image](https://user-images.githubusercontent.com/23707134/216692453-feb7d3d4-97f6-43d6-bb6a-2132bc2b5829.png)

**Comment by GiorgioUghini** [comment]
Changing line 134 in realtime_device_data_sensor.py from
https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/custom_components/fusion_solar/fusion_solar/realtime_device_data_sensor.py#L134
to `STATE_CLASS_TOTAL_INCREASING` would solve. 
But, I'm not sure if doing so would break other sensors which may be correctly identified as "total" and should not be "total_increasing".

**Comment by tijsverkoyen** [comment]
I have merged your PR.
I will create a PR in a few moments
