### ISSUE TITLE
Can't add inverters active power to the energy dashboard as a solarproduction unit

### ISSUE THREAD

**Issue by KrickGregory** [tijsverkoyen/HomeAssistant-FusionSolar#55]
Dear Tijs,

First of all thanks for the very nice add on. Just what I was looking for. One little issue I have. I have imported with API 5 devices and 136 enteties. All works very well and I can make graphs with my inverters production as well.
But if I want to add my inverters production to the energy dashboard as a solar production unit I don't get the sensor.2101073803hvk7000592_active_power in the dropdown menu.
Any idea what I'm doing wrong? 

Kind regards,
Gregory

**Comment by tijsverkoyen** [comment]
Home Assistant expects an entity with a unit in kWh. Active Power is in kW, that is why you can’t use it.

**Comment by KrickGregory** [comment]
Damn :-( Any idea if it's possible to make a helper with the value devided by 1000?

**Comment by tijsverkoyen** [comment]
Why? kWh is not kW / 1000
It is just not the same.
Why don’t you use the lifetime value?

**Comment by KrickGregory** [comment]
Oh.  Sorry.  Sunday evening.  My  mistake. I'll have a look tomorrow. Let you know.

**Comment by tijsverkoyen** [comment]
I think you should look for “Total Yield”

**Comment by KrickGregory** [comment]
Total Yield did it. Thanks. I'll buy you a coffee.

**Comment by tijsverkoyen** [comment]
Thx! Really appreciated!
