### ISSUE TITLE
Error when instaling

### ISSUE THREAD

**Issue by laurh77** [tijsverkoyen/HomeAssistant-FusionSolar#56]
Hello
I try to install in "Kiosk" mode
No error received but no entity created
In the logs: 
Logger: homeassistant.setup
Source: setup.py:320
First occurred: 7:57:50 PM (1 occurrences)
Last logged: 7:57:50 PM

Unable to prepare setup for platform fusion_solar.sensor: Platform not found (cannot import name 'UnitOfElectricCurrent' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

Anybody can help me ?
Thank you

**Comment by tijsverkoyen** [comment]
Which version of Home Assistant are you using?
I suspect it is not up to date.

**Comment by tijsverkoyen** [comment]
You will need at least Home Assistant Core 2023.1
See https://developers.home-assistant.io/blog/2022/12/05/more-unit-enumerators/

**Comment by laurh77** [comment]
Thank you 
Updating the HAS solved the problem
