### ISSUE TITLE
supress warning error in logs

### ISSUE THREAD

**Issue by catalinbordan** [tijsverkoyen/HomeAssistant-FusionSolar#57]
Hello,

Can you please make to not show anymore this kind of informative message in logs?
It came up after sunset.

Logger: custom_components.fusion_solar.fusion_solar.energy_sensor
Source: custom_components/fusion_solar/fusion_solar/energy_sensor.py:66
Integration: FusionSolar ([documentation](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar), [issues](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues))
First occurred: 21:11:54 (1 occurrences)
Last logged: 21:11:54

sensor.golesti_ehnahtdaxplzjrxmygmfegjedl7b77im_total_lifetime_energy: not producing any power, so not updating to prevent positive glitched.

**Comment by tijsverkoyen** [comment]
You can ignore this warning.
I you don’t want to see warning you can change the log level in Home Assistant: https://www.home-assistant.io/integrations/logger/

**Comment by catalinbordan** [comment]
Thank you for your time,
I don't have custom settings(filters) for logger until now.
IMHO this messages are info or debug category. If indeed it is a warning, should I do something to solve it?
thanks,

**Comment by tijsverkoyen** [comment]
You should not do anything. It is a warning to let you know the entity is not updated.

**Comment by catalinbordan** [comment]
I see,

so we need to change it like this?

                if realtime_power == '0.00':
                    _LOGGER.**debug**(
                        f'{self.entity_id}: not producing any power, so not updating to prevent positive glitched.')
                    return float(current_value)

Can I propose a PR?  wifth debug/info?
thanks

**Comment by tijsverkoyen** [comment]
But why?
It is a warning to let you know the entity is not updated. I think this is usefull information, no?

**Comment by catalinbordan** [comment]
In my opinion is spamming my logs. I already have until now 24 occurrences with this message for this evening.
I personally prefer to see in logs only the things I should take some actions.

**Comment by tijsverkoyen** [comment]
Then info would be the better level for your PR

**Comment by catalinbordan** [comment]
Done.

**Comment by tijsverkoyen** [comment]
Your PR is merged. I will create a new release later today.

**Comment by catalinbordan** [comment]
thanks for let me know.
