### ISSUE TITLE
set forced battery charge

### ISSUE THREAD

**Issue by sorenbek** [tijsverkoyen/HomeAssistant-FusionSolar#59]
Hi.
Is it possible to set forced battery charge, forced discharge (and stop forced charge and discharge) as described in Northbound Interface Reference 7.3.6 via the FusionSolar integration?

**Comment by tijsverkoyen** [comment]
@sorenbek the documentation I have goes only to 5. See: https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/docs/smartpvms-v500r007c00-northbound-interface-reference.pdf
Feel free to upload the docs so I can see what is possible.

**Comment by sorenbek** [comment]
@tijsverkoyen here are the documentation I got with the api account:

[iMaster NetEco V600R023C00 Northbound Interface Reference-V7(SmartPVMS).pdf](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/files/10704633/iMaster.NetEco.V600R023C00.Northbound.Interface.Reference-V7.SmartPVMS.pdf)

**Comment by tijsverkoyen** [comment]
In that documentation it seems like all endpoints are on `https://x.x.x.x:27200/rest/openapi/pvms/v1` while this integration is using `https://xxxx/thirdData/`. At this point it is not that able to mix these requests.

I suspect that `x.x.x.x:27200` is also the IP of the local installation, but I could be wrong.

I don't think this is a feature that will land soon in this integration.

**Comment by sorenbek** [comment]
too bad, that would be a neat feature.
But thanks for looking into it, and thanks for your great work on the integration

**Comment by tijsverkoyen** [comment]
I will leave this issue, if other people want this feature too I can have a look if there is a way. But at the moment I don't have the time to research this further.

**Comment by tijsverkoyen** [comment]
@sorenbek thx! really appreciated!
