### ISSUE TITLE
Realtime Power missing

### ISSUE THREAD

**Issue by kamil996** [tijsverkoyen/HomeAssistant-FusionSolar#6]
Hello. I’ve configured with OpenAPI credentials - works, but there is no entity with Realtime Power to check production right now.
How much entities it should generate? I got only 4 - production daily, monthly, yearly, all time.

Much appreciate Your brilliant work, regards.

**Comment by tijsverkoyen** [comment]
@kamil996 The integration generate 2 devices:
1. model = station. With 4 entities linked. These contain the production numbers.
2. model = residential inverter xxx. With 1 entity linked, this entity shows the realtime power

Could you tell me which inverter you have?
Are you willing to share your OpenAPI credentials with me, so I can debug? If so: mail them to me `fusionsolar [at] verkoyen.eu`.

**Comment by kamil996** [comment]
@tijsverkoyen thanks for answer. I've emailed You details.

My setup is two inverters:
1. HUAWEI SUN 2000-8KTL-M0
2. HUAWEI SUN 2000-12KTL-M0

**Comment by tijsverkoyen** [comment]
Thx, will probably be something I will debug next week.

**Comment by tijsverkoyen** [comment]
The devices listed in your "station" are not "residential inverters", but "string inverters". 

I have added support: https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/7. I will create a release in a few minutes.

I also see you have a battery in your setup? Would you be ok if I use your credentials to add support for batteries? If I have the time ;-)

**Comment by tijsverkoyen** [comment]
The release has been made. 
Let me know if this fixes your issue. If not: reopen the issue please.

**Comment by kamil996** [comment]
Feel free to use my account now and in future cases, to add functionalities, debug etc. :) 
About battery: i dont have it physically, but somehow its visible in my setup. Maybe support can be added anyway :)

**Comment by giovanni97bs** [comment]
@tijsverkoyen 
Hi, i have also implemented your integration.
I note that I also have installed batteries and I can see grid and house current consumption and history. Would love to see them implemented. I can share my account also if you might need for development

**Comment by tijsverkoyen** [comment]
@giovanni97bs feel free to share your credentials via `fusionsolar [at] verkoyen.eu`.
