### ISSUE TITLE
Fusion solar 

### ISSUE THREAD

**Issue by lucab115** [tijsverkoyen/HomeAssistant-FusionSolar#61]
Ho installato la guida come da voi suggerito con kiosk ma non riesco a vedere la carica delle batterie come mai?

**Comment by tijsverkoyen** [comment]
Could you translate your question to English please, as I don't know what you mean.
I think you are using kiosk, and something about a battery?

**Comment by lucab115** [comment]
Hi Tijs i write in english. Can you help me with home assistant for
configuration?
Thanks
Luca

Il Gio 16 Feb 2023, 11:45 Tijs Verkoyen ***@***.***> ha
scritto:

**Comment by tijsverkoyen** [comment]
Can you share the kiosk url you have used?

**Comment by lucab115** [comment]
Sorry but you want my koisk for what?

Il Gio 16 Feb 2023, 17:13 Tijs Verkoyen ***@***.***> ha
scritto:

**Comment by lucab115** [comment]
Hi Tijs here my kiosk. Please help me for the correct configuration on my
home assitant. Can you try to found a openapi huawei so I delete the kiosk
and I use the openapi.

I attend your answer thanks
Luca


https://region03eu5.fusionsolar.huawei.com/pvmswebsite/nologin/assets/build/index.html#/kiosk?kk=Hq53kezkfIc5Kxh200IxNFrirHpr5KNa

Il Gio 16 Feb 2023, 17:13 Tijs Verkoyen ***@***.***> ha
scritto:

**Comment by tijsverkoyen** [comment]
In the kiosk there seems no data available for the battery.
I suggest you switch to the Open API mode of the integration.

**Comment by lucab115** [comment]
Can you help me for obtein a open api mode huwawei? Please im a principiant

Il Ven 17 Feb 2023, 11:30 Tijs Verkoyen ***@***.***> ha
scritto:

**Comment by tijsverkoyen** [comment]
You will need to contact Fusion Solar or your installer. See https://github.com/tijsverkoyen/HomeAssistant-FusionSolar#openapi
