### ISSUE TITLE
FUSION SOLAR 

### ISSUE THREAD

**Issue by lucab115** [tijsverkoyen/HomeAssistant-FusionSolar#62]
Hi sorry for my bad english. I translate what I write in italian..... I try to install fusion solar in home assistant, but you say that if i go to fusion settings i can found battere and something else, but I found only instant power and also 4 other value please im a principiant can you help me thanks

**Comment by tijsverkoyen** [comment]
This is the same issue as in https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/61
