### ISSUE TITLE
Entities reporting "unknown"

### ISSUE THREAD

**Issue by pretor2113** [tijsverkoyen/HomeAssistant-FusionSolar#63]
Hi!
I just finished setting up the integration, everything worked fine. However, every entity reports "unknown". 
![image](https://user-images.githubusercontent.com/115184868/219419417-52cb19a6-6d40-4e9e-b256-396f1c3260eb.png)
 Any ideas as to why this might happen? 
Thanks!

**Comment by tijsverkoyen** [comment]
Can you check the logs?
Probably because the data is not provided by the API.

**Comment by pretor2113** [comment]
The logs don't show any errors on the integration. Could this "unknown" report be caused by missing permissions in the OpenAPI account creation? Should I ask my installer to recheck the permissions on my API account?

**Comment by pretor2113** [comment]
It was a permission issue. After the installer rechecked those, everything is reported OK. Thank you for this amazing integration!

**Comment by tijsverkoyen** [comment]
Glad it is resolved.
