### ISSUE TITLE
Help with OpenAPI account

### ISSUE THREAD

**Issue by jvcsw** [tijsverkoyen/HomeAssistant-FusionSolar#77]
Hi, 

could someone tell me how to create an account for the OpenAPI?

Does only one installer have permission to create it?

Are these the correct steps?

https://www.youtube.com/watch?v=L7BOo96cLaw

If I have to ask the installer, I have to tell him exactly what to do.

Thanks

**Comment by tijsverkoyen** [comment]
Thx to [@aretokas](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/75) the documentation has been updated just a few moments ago.
You can find all steps required at https://github.com/tijsverkoyen/HomeAssistant-FusionSolar#northbound-api--openapi

**Comment by jvcsw** [comment]
Thanks

**Comment by jvcsw** [comment]
Hi again,

I need to change this url?

![imagen](https://user-images.githubusercontent.com/37216513/224763780-56ddd00a-e279-4160-ad6f-f9dee0a99762.png)

**Comment by jvcsw** [comment]
But, by default, is it the correct url?

Because the login fails and I don't know the reason.

**Comment by tijsverkoyen** [comment]
Your url depends on your installation.
You should use the url that you use to login on the web interface.
