### ISSUE TITLE
Getting the most out of this great add-on

### ISSUE THREAD

**Issue by arohl** [tijsverkoyen/HomeAssistant-FusionSolar#79]
I have to say that I have been overwhelmed by all the data provided by this add-on. What I am looking for is a guide showing what the key values mean and how to use/monitor within homeassistant. I don't think such a thing exists but I am happy to write one provided I can can the help I need to explain some of the things. One of the first things I would like to do is create a visualisation like the one in the official app i.e.
 
![IMG_2661](https://user-images.githubusercontent.com/10984236/224473584-df643c63-1877-4b12-b9bb-8cd25a96c9a5.jpeg)

I think I have figured out where to get the battery data from (create two template sensors from battery_1_charge_discharge_power) but have a number of further questions. I don't think anyone would disagree that a document showing ways to use the integration in homeassistant is a good idea, so my question is what is the best way to ask questions of the community on my journey? The answer of course could be this issue ;-)

**Comment by sorenbek** [comment]
It would be nice to have a guide.
[Pedro_Trancoso] has made a description on how he made a app-like active power diagram. I think the template sensors he made could be used to make your visualization. the thread is about the 'Solar inverter huawei 2000L' Integration but there is a lot to learn for a fusion solar user.  https://community.home-assistant.io/t/integration-solar-inverter-huawei-2000l/132350/2110

**Comment by arohl** [comment]
Great link! I'll do some exploring...

**Comment by tijsverkoyen** [comment]
Feel free to create PR's that ad more documentation, or with useful links, ...

**Comment by aretokas** [comment]
I've already got it on my list of things to do to generate some code that allows us to replicate the FusionSolar graphs. I've spent a lot of time making some notes, but haven't really gotten it to the point where I'm happy to start writing code :). I will see if my notes are worth sharing or just mindless ramblings when I get home later.

**Comment by arohl** [comment]
I have made some headway. The integration with the energy panel is working for my solar/battery system. It wasn't totally obvious though. Do others also use:
- Grid consumption = Meter-1 - Reverse active energy
- Return to grid = Meter-1 - Active energy (forward active energy)
- Solar production = Home - Total Current Day Energy
- Battery energy in = Battery-1 - Charging capacity
- Battery energy out = Battery-1 - Discharging capacity
If so, I will write it up

**Comment by arohl** [comment]
![IMG_2666](https://user-images.githubusercontent.com/10984236/226288842-9a803166-a2ee-45f4-a891-7428ee1a3e59.jpeg)

I haven't added Consumed from PV yet as I can't see why that's useful and am thinking of adding in grid consumption and production

**Comment by tijsverkoyen** [comment]
👍 Looks good!
Feel free to create a PR to improve the docs with a description on how you have configured everything

**Comment by arohl** [comment]
Should this be added to the README.md or create a seperate doc?

**Comment by tijsverkoyen** [comment]
README.md is goof. If needed I will split it later.

**Comment by tijsverkoyen** [comment]
As there is no update on this I will close this issue.
