### ISSUE TITLE
No entiteiten in HA

### ISSUE THREAD

**Issue by tobyknobi** [tijsverkoyen/HomeAssistant-FusionSolar#84]
I have installed the fusion solar integration via HACS and i am running HA in a docker. 
The kiosk mode worked fine.
 Now i finely got the api account from northbound through my installer. They have confirmed that its should be oke.
Via postman i can login in. https://intl.fusionsolar.huawei.com/thirdData/ 
I am new to postman. If i want the station list i get every time, user needs to re login.
(maybe do to 1 account?).
After deleting the kiosk mode and reinstall the integration with the supplied info from my solar installer. its says oke but then nothing happens.
no entiteiten.
There is nothing else what i can configure. or do i need to install some more or activate anything

**Comment by tijsverkoyen** [comment]
Do you use the same credentials anywhere else?
Have you checked the logs in Home Assistant?
Are you willing to share your credentials with me via email `fusionsolar [at] verkoyen [dot] eu`

**Comment by tobyknobi** [comment]
Yes I am willing to share with you my info

Dit is privé mail??
Kunnen nu in Nederlands verder?

Op di 11 apr. 2023 18:25 schreef Tijs Verkoyen ***@***.***>:

**Comment by tobyknobi** [comment]
Traceback (most recent call last):
File
"/config/custom_components/fusion_solar/fusion_solar/openapi/openapi_api.py",
line 54, in get_station_list
response = self._do_call(url, json)
File
"/config/custom_components/fusion_solar/fusion_solar/openapi/openapi_api.py",
line 189, in _do_call
raise
FusionSolarOpenApiErrorInvalidAccessToCurrentInterfaceError(json_data[ATTR_MESSAGE])
custom_components.fusion_solar.fusion_solar.openapi.openapi_api.FusionSolarOpenApiErrorInvalidAccessToCurrentInterfaceError:
Invalid access to current interface!
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 304, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/fusion_solar/sensor.py", line 750, in
async_setup_entry
stations = await hass.async_add_executor_job(api.get_station_list)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in
run
result = self.fn(*self.args, **self.kwargs)
File
"/config/custom_components/fusion_solar/fusion_solar/openapi/openapi_api.py",
line 57, in get_station_list
return self.stations()
File
"/config/custom_components/fusion_solar/fusion_solar/openapi/openapi_api.py",
line 85, in stations
response = self._do_call(url, json)
File
"/config/custom_components/fusion_solar/fusion_solar/openapi/openapi_api.py",
line 189, in _do_call
raise
FusionSolarOpenApiErrorInvalidAccessToCurrentInterfaceError(json_data[ATTR_MESSAGE])
custom_components.fusion_solar.fusion_solar.openapi.openapi_api.FusionSolarOpenApiErrorInvalidAccessToCurrentInterfaceError:
Invalid access to current interface!

Op di 11 apr. 2023 18:47 schreef Toby Eleveld ***@***.***>:

**Comment by tobyknobi** [comment]
have send you an email with credencials and stop the integration on HA

**Comment by tijsverkoyen** [comment]
Jep, thx. I will try to test this week.

**Comment by tijsverkoyen** [comment]
I think your installer forgot to give you access to the Plant list call.
Both `/thirdData/stations` and `/thirdData/getStationList` calls return in a 401 - Invalid access to current interface!

**Comment by tijsverkoyen** [comment]
I will close this issue. Feel free to reopen it if it is not resolved after your installer has checked that you have access.

**Comment by tobyknobi** [comment]
Hi there tijs,

If you have time can you check if it works on your side?

All setting in Northbound should be good.

I am not a professional on API systems.

But I need to know if there is something wrong with my home assistant
Installation.
Does it matter if kiosk mode is on?

Regards Toby

Op wo 12 apr. 2023 15:37 schreef Toby Eleveld ***@***.***>:

**Comment by tijsverkoyen** [comment]
I'm pretty sure everything is fine at my end, as I am using the integration on a daily base.
If have checked with your credentials again:
* Login: works
* Retrieving the stations does not work. Not by calling `getStationList` nor `stations`. The error I get is: `Invalid access to current interface!`. Which indicates that there is something wrong with the rights for your credentials.

This has nothing to do with your Home Assistant installation.

If your installer can't resolve the issue, I suggest you contact `eu_inverter_support@huawei.com`.

**Comment by tobyknobi** [comment]
Thanks you.

I had the same issues.
But I didn't know it on my end or installers end. Or home assistant end.

I thank you for your time and quick response
Toby

Op di 25 apr. 2023 16:56 schreef Tijs Verkoyen ***@***.***>:

**Comment by tobyknobi** [comment]
Hi tijd.

Just letting you know. The problem is solved.

The installer forgot 1 thing

Thanks for your help and your integration

Groetjes Toby

Op di 25 apr. 2023 19:14 schreef Toby Eleveld ***@***.***>:

**Comment by tobyknobi** [comment]
Well solved.

I do get entities. But it stays on unknown everything.

Or do I have to wait a bit longer

Regards
Toby

Op di 2 mei 2023 14:11 schreef Toby Eleveld ***@***.***>:

**Comment by tijsverkoyen** [comment]
no you should not. Do you see anything in the logs?

**Comment by tobyknobi** [comment]
I do need to say.

After a restart of the docker container. There are no more fusion messages.

In the log (also debug)

All clean.
So there must be that the installer has forgotten something.

Op wo 3 mei 2023 21:27 schreef Toby Eleveld ***@***.***>:
