### ISSUE TITLE
Integration does not work with the Huawei iSitePower-M

### ISSUE THREAD

**Issue by wesleychannon** [tijsverkoyen/HomeAssistant-FusionSolar#85]
Greetings!

When trying to use this integration with the Huawei iSitePower-M it's able to pick up the device(s), but none of the sensors pull through.

I had a bit of a dig at the NBI and the endpoints it uses. The device ID's don't seem to yield data, so I suspect the issue is upstream (with Huawei) and not with this integration. Followed their documentation - got auth working, then queried for devices, etc. It's just the sensor data that doesn't have results. Suspect their NBI isn't 'complete' when it comes to this device (for now). Using Huawei's Fusion Solar website does yield results though - same with the mobile app, just not the NBI (maybe I'm doing something wrong?).

If you're keen on playing around with iSitePower-M NBI integration, let me know, and I'll give you access to it's data on Huawei's Fusion Solar website (the NBI). The iSitePower-M is another all-in-one inverter from Huawei, presumably their next generation solution.

**Comment by tijsverkoyen** [comment]
Where can I find the documentation?

**Comment by wesleychannon** [comment]
I suspect this may be similar to the documentation you have already.  These are the URL's I'm using:

https://support.huawei.com/enterprise/en/doc/EDOC1100261860/d4ee355a/v6-interface-reference
https://support.huawei.com/enterprise/en/doc/EDOC1100241338

**Comment by ZainAjam** [comment]
I have this problem too. I used the integration both through kiosk and open api mode, and both instances resulted in a successful connection to fusion solar but no devices or entities come through the integration - see image attached.

![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/32865278/232c5be0-1f1b-4023-bfe6-b2f58f5c9ad9)

**Comment by ZainAjam** [comment]
> I have this problem too with my Huawei Power M unit running on fusion solar. I used the integration both through kiosk and nortbound / open api mode, and both instances resulted in a successful connection to fusion solar but no devices or entities come through the integration - see image attached.
> 
> ![image](https://user-images.githubusercontent.com/32865278/244931425-232c5be0-1f1b-4023-bfe6-b2f58f5c9ad9.png)

Managed to get the entities and devices to feed through by enabling everything in the norhtbound api setup, however the main device's entities are all Unknown or Zero

**Comment by tijsverkoyen** [comment]
If you are willing to share your credentials I can look into it. But I don't promise anything, and it will probably take a while as I don't have much time at the moment.
Feel free to share your credentials via mail: fusionsolar [at] Verkoyen [dot] eu

**Comment by fredclappen** [comment]
Hi tijsverkoyen.

I’m having the same issue ZaneAjam.
The device is showing with its modules but no energy data is coming through.
I have also tried both Northbound API and Kiosk.

Would it be possible to investigate if I share the Northbound credentials with you?

**Comment by tijsverkoyen** [comment]
@fredclappen feel free to share the credentials.

Can you also tell me if you are able to log in on https://intl.fusionsolar.huawei.com with these credentials and seeing data?
When you tested the integration, which url did you use in the Host field?

**Comment by tijsverkoyen** [comment]
It seems that there is some regional thing in place that makes it impossible for me to connect to any iSitePower-M installation from Belgium. Which makes it very difficult to do any development for supporting iSitePower-M installations.

If you have an installation and are living in Belgium/Europe and are willing to share credentials. Please contact me

**Comment by MarjoCo** [comment]
Hi, we have: Huawei Sun 10KW and got only 5 interfaces coming through. Tried both Kiosk and open API. The grid related are not coming through at all.

**Comment by tijsverkoyen** [comment]
Where do you live? In Europe? If so: are you willing to share your credentials with me?
