### ISSUE TITLE
Efficiency graph in bar chart

### ISSUE THREAD

**Issue by kzajac83** [tijsverkoyen/HomeAssistant-FusionSolar#86]
Hello.

I made integration with inverter via Huawei API and all seems working fine expect visualisation results and efficiency in percents. 

Can you please change efficienty from bar style to normal graphs like current, voltage or Hz? My view is:

![image](https://user-images.githubusercontent.com/50861081/231734203-fcbd0021-3748-4233-8aa6-071d3f51530e.png)

Make zoon in time this looks like that - it is not user friendly to read:

![image](https://user-images.githubusercontent.com/50861081/231734427-ae3be55b-91e5-4e93-8faf-314c2124cf77.png)

My inverter is SUN2000-8KTL-M1

**Comment by tijsverkoyen** [comment]
This is a visualisation done by Home Assistant for the entity.
I think you can add it to your dashboard with a line graph.

**Comment by kzajac83** [comment]
I'm quite new user so sorry for addressing topic to wrong queue however what decide type of graphics? Mayby some parameter of entities created under integration decide of it?

**Comment by tijsverkoyen** [comment]
You can add a Sensor Card to your dashboard and it will show a graph:
![graph](https://user-images.githubusercontent.com/250042/231811066-e25eb0c9-1cc6-42ee-ac42-198f4e746871.png)
You need to edit your dashboard and add a Sensor Card, you can select the Inverter efficiency % (manufacturer) entity.

But! you are right. It should be possible to instruct Home Assistant to show a line graph instead. I will look into that.

**Comment by kzajac83** [comment]
General is because there is no unit of measuer, not sure have looks like variables but if % then this specail char has been can be interpeter wrong and this is reasin why missing UoM and HA interpreted it as string value. Can you somehow add UoM ??

**Comment by tijsverkoyen** [comment]
I know, you are right. I'm working on the fix at the moment. Will do a release later today.

**Comment by tijsverkoyen** [comment]
Pull Request is ready: https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/88
Releasing in a few moments.

**Comment by kzajac83** [comment]
Is working, thank you for fix
