### ISSUE TITLE
Integration create too many entities

### ISSUE THREAD

**Issue by kzajac83** [tijsverkoyen/HomeAssistant-FusionSolar#87]
Hello.

Integration pass fine via API Huawei however after it I got more than 100 entities where 59 I need hide. 

![image](https://user-images.githubusercontent.com/50861081/231735737-2fee6a7f-3449-4d8c-8c87-ce0ce42a9d43.png)

Reason is because my inverter have only 2 MTTP/PV channels however integration create 25 PV/MTTP "virtual" sockets. 

![image](https://user-images.githubusercontent.com/50861081/231735884-a6d98518-bd47-43f5-9c38-8a5b9a41ea02.png)

Due to can you check inverter model and create PV inputs and connectet entities according how many real inputs have inverter? In my cause I have model SUN2000-8KTL-M1

**Comment by tijsverkoyen** [comment]
No, this is not possible. As these are all returned from the API. And there is no way of knowing which ones are in use.
You can only add the ones you need to your dashboard.

**Comment by kzajac83** [comment]
But in diagnostic ther is entitie "Inverter model", then simple mapping table can by keep and decide how many entites create

![image](https://user-images.githubusercontent.com/50861081/231748960-e4b15895-5467-4d55-9e83-828d7ebbeb75.png)

**Comment by tijsverkoyen** [comment]
That would mean I need to maintain a list of alle inverters.
My current experience with Huawei support are not that good, so retrieving a list of all possible models and how many points there are available will not be easy.

To be honest I don't see the problem. You should only add the entities you want to see to your dashboard and don't bother about the other entities. You don't need to add them all.
