### ISSUE TITLE
Alarms and automation 

### ISSUE THREAD

**Issue by kzajac83** [tijsverkoyen/HomeAssistant-FusionSolar#90]
Hello.

Fusion Solar add-on is working in HA, thank you for your work however I have issue with my physical inverter due to too high voltage in grid that cause shutdown. 

In Fusion Solar portal for today I see this alarms:

![image](https://user-images.githubusercontent.com/50861081/235445685-011153b8-19ef-4c0a-a330-b217342176da.png)

![image](https://user-images.githubusercontent.com/50861081/235444574-f96fef65-7cb1-445e-859a-85ce05afd75b.png)

In HA first of all I see two statuses

![image](https://user-images.githubusercontent.com/50861081/235444884-3063aaae-1901-4c09-aa11-c578298c8142.png)

One is empty and second is:

![image](https://user-images.githubusercontent.com/50861081/235445445-d4fb36d9-a297-405c-b564-e8843ceee365.png)

What is strange do not see change about 13:01 in HA and missing shutdown status like form yesterday:
![image](https://user-images.githubusercontent.com/50861081/235446072-adb71da5-2c4b-4326-a691-46e4b817eec8.png)

I try build automation notification but not working, my current notification automation config is:

`
alias: Powiadomienie inwerter XXXXXX Shutdown
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.inverter_1_inverter_status
    to: "changed to Shutdown: unexpected shutdown"
condition: []
action:
  - service: notify.notify
    data:
      data:
        actions:
          - action: URI
            title: Open Url
            uri: /energy
      message: Inwerter XXXXX wywalony
      title: Inwerter XXXXX Shutdown
mode: single
`

I try build automation base on below status string of inverter  but I general not working: 

"changed to Shutdown: unexpected shutdown"

"Shutdown: unexpected shutdown"

"unexpected shutdown"

Due to I jump to dev in HA tool and found this:

![image](https://user-images.githubusercontent.com/50861081/235444116-b2dca610-ac18-49fc-99bc-c0154b9a90a9.png)

and seems status in numerical valu, what should I use in my automation?

Summary

1. It is possible download to HA Alarms?
2. Why I do not see shutdown status of inverter for today? In Fusion Solar portal for yesterday and today status is the same - grid over-voltage but yesterday got shutdown status but today no?
3. Do not see change status about 13:01 today (now is almost 14:00 when I write this and still no change status)
4. It is possible that some statuses do not download to HA? How to check what status are visible in API for today? I'd like compare with HA statuses? Can ask for short instruction?
5. How I can build notification about over-voltage / shutdown in HA? Should use string or numerical value?

BR, Krzysiek

**Comment by tijsverkoyen** [comment]
All data that is exposed through the following calls is available in HA, and is updated regularly
*  `/thirdData/getDevRealKpi`
* `/thirdData/getKpiStationYear`

Note that this pulled from the API, and not pushed from the API to HA. So there can be delays, or missing information if the status changes between these intervals. For instance if the update is x:10, x:20, x:30, ... and the status changes at x:11 and changes back to another status at x:19, that won't be visible in HA.

You can find the status codes and their translation at: [custom_components/fusion_solar/translations/en.json](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/custom_components/fusion_solar/translations/en.json#L59)

All the information that is used to develop this integration comes from [master/docs/imaster-neteco-v600r022c00-northbound-interface-reference-v6.pdf](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/docs/imaster-neteco-v600r022c00-northbound-interface-reference-v6.pdf).

I think you will need to use the numerical values as the translations happen through the HA system, see [Translating the state of entities](https://developers.home-assistant.io/blog/2022/12/01/entity_translations/) for more information

**Comment by tijsverkoyen** [comment]
@kzajac83 was the information I gave clear? I will close this issue, but feel free to reopen the issue if needed.
