### ISSUE TITLE
real time power vs active power

### ISSUE THREAD

**Issue by tobyknobi** [tijsverkoyen/HomeAssistant-FusionSolar#92]
Not sure if it is a issue,
But they are the same . Same results. (real time power vs active power)
I am missing the consumption (house).

Thanks for the great integration btw

**Comment by tijsverkoyen** [comment]
Yeah, I think that is one I added for more backwards compatibility, or it is one from the Kiosk mode. Not really sure.
Alle data that is documented is returned by the integration. So if you are missing data: provide me with the correct documentation and point to the missing paramater so I can add it.

**Comment by tijsverkoyen** [comment]
@tobyknobi any update? Ok if I close this issue?
