### ISSUE TITLE
Home energy consumed

### ISSUE THREAD

**Issue by jvcsw** [tijsverkoyen/HomeAssistant-FusionSolar#94]
Hi again,

thanks for the integration and fix the last issue.

One question:

In this integration, is there any way to get the home energy consumed (energy from fv + energy from grid)?

Total energy consumed by day, month, year like this (but with consumed  energy):

![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/1b46a559-1e9f-4411-932c-b5e70f293c8e)

Thanks

**Comment by tijsverkoyen** [comment]
@jvcsw if you use the Open API version (not the kiosk mode) there is a lot of data available.
For the correct descriptions, see: https://github.com/tijsverkoyen/HomeAssistant-FusionSolar#what-do-all-entities-mean

**Comment by jvcsw** [comment]
Yes, I'm using Northbound API / OpenAPI, but I don't see this values.

**Comment by tijsverkoyen** [comment]
There are the items that are exposed: 
- https://support.huawei.com/enterprise/en/doc/EDOC1100261860/3557ba96/real-time-device-data-interface
- https://support.huawei.com/enterprise/en/doc/EDOC1100261860/4d0ba389/yearly-plant-data-interface

If you don't see them there is something wrong with your Open API configuration. Check Settings → Devices & Services → Fusion Solar → Click "xx entities" to see all the entities that are exposed.

**Comment by jvcsw** [comment]
Hi, 

I have 4 entities, this is right, but you see the image now from fusionsolar webpage please:

![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/46ad585c-2baa-4542-aea0-12e9a6100f15)

The pink circles are values that I found in your integration, Ok.
The orange circles are values that can be calculed with other previous values, Ok.
But the yellow circles are values that I don't found in the integration.

For this reason, my request was add the consumption values in the integration like total production values.

![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/8ce760ee-e92a-42b4-8266-cbf54c1a462a)

Thanks

**Comment by tijsverkoyen** [comment]
@jvcsw that is in kiosk mode?

**Comment by jvcsw** [comment]
> @jvcsw that is in kiosk mode?

No, using Open API

https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/94#issuecomment-1554228250

**Comment by tijsverkoyen** [comment]
Could you mail `fusionsolar [at] Verkoyen [dot] eu` your credentials? Then I will have a look, but no promises.

**Comment by tijsverkoyen** [comment]
Some research, mostly for myself

Lifetime: sum of all collections in /thirdData/getKpiStationYear since the start of the station
Current year: /thirdData/getKpiStationYear

Consumed = use_power

**Comment by jvcsw** [comment]
In my case the most important is from lifetime. It would be interesting to have it as shown in energy productions (lifetime, year, month, day).

**Comment by tijsverkoyen** [comment]
@jvcsw see https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/95
Would you be able to test this?

**Comment by jvcsw** [comment]
mmm... How can I test it?

A new version does not appear in Hacs.

**Comment by jvcsw** [comment]
Now there are more sensors:

![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/dc668c30-1431-45a3-b024-94653f2fddcd)

![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/fb181e09-9467-4d87-b6de-90765f9fec59)

Desconegut = not available

**Comment by tijsverkoyen** [comment]
The ones that are not available are the ones therefor the API does not return data. Eg:

```
...
       {
            "collectTime": 1672527600000,
            "stationCode": "XXXXXX",
            "dataItemMap": {
                "radiation_intensity": null, # Global Irradiation
                "installed_capacity": 0.0,
                "use_power": 1031.29,
                "inverter_power": 1558.06,
                "reduction_total_tree": 1.044,
                "power_profit": 348.124,
                "theory_power": null, # Theoretical yield
                "reduction_total_coal": 0.643,
                "perpower_ratio": null, # Specific energy (kWh/kWp)
                "reduction_total_co2": 0.764,
                "ongrid_power": 683.98, 
                "performance_ratio": null # Performance ratio
            }
....
```

Can you check if the values match with what you see on your portal? There can be differences, but they should be in the same range.

**Comment by jvcsw** [comment]
Yes, I have reviewed and I do not see any errors, but I have done it very quickly. 
I'll check everything when I have more time.

Thank you so much

**Comment by tijsverkoyen** [comment]
Ok, let me know if you had the time to review it more in detail. If everything works fine I will create a release.

**Comment by tijsverkoyen** [comment]
@jvcsw the names for the new entities are fixed in https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/95/commits/3b2d3cb624f122018acc2dbed725f88386712896

Total Current Day Energy, Total Current Month Energy and Total Lifetime Energy are coming from another endpoint. The Total Current Year Energy is based on the `/thirdData/getKpiStationYear`, this was added to be able to give the same information that is available in Kioskmode.

With the new entities all data from the `/thirdData/getKpiStationYear` is exposed. So that is why there are some duplicate entities with other names.

I will create a release later this week. Let me know if there any issues with these changes.

And a big thanks for helping me out to improve the integration.

**Comment by tijsverkoyen** [comment]
I don't create the endpoints, these are what Huawei Fusion Solar exposes.

I will keep the entities for backwards compatibility, as probably a lot of users use them and have collected statistics for these entities.

**Comment by jvcsw** [comment]
Yes Yes, I know that the endpoints are from fusionsolar, I was just asking if there was one for each range.

**Comment by tijsverkoyen** [comment]
There are, but I need to look into that. And it will also increase the number of calls that are made. And Huawei Fusion Solar is becoming more strict with the rate limiting.

I have created an issue: https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/96
Feel free to give your opinion.

**Comment by jvcsw** [comment]
Hi @tijsverkoyen,

I found these sensors without units (kWh):

![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/9596bf11-d831-49d4-908f-34f9f32d3344)

![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/4712003a-581d-457f-b70a-ea83c30133dc)

Thanks

**Comment by jvcsw** [comment]
Ok, you're right, I was confused.

Well, if so, these two annual and lifetime values are missing

![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/23889833-aa99-4ffc-9366-c04e3cff93ed)

**Comment by tijsverkoyen** [comment]
Yeah, I have added all data items I found in the documentation. Probably these are calculations based on other data?

**Comment by jvcsw** [comment]
I don't know how.

There are these values only (lifetime, in this case):

![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/583cb61a-0a8b-453a-9caf-d4f2223db9af)

The orange value can be calculated, but the red ones? Missing at least one value.

![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/783dbf25-e8aa-45df-b217-12aeda6ebae4)

**Comment by tijsverkoyen** [comment]
@jvcsw probably best to contact Fusion Solar Helpdesk () and ask them where these values are exposed through the API.

**Comment by jvcsw** [comment]
Hi, this is the Huawei response:

_Nr1 :production minus fed to grid ( from perspective of feeding to grid )
Nr 2:consumtion minus from grid value (from perspective of purchasing from grid)
Nr 3: consumption from grid .

Best regards_

But I don't see the value of "from grid". Exist a lifetime/year sensor with "Feed-in energy" but not a with "Feed-out energy".

For

**Comment by tijsverkoyen** [comment]
Beter to ask them which endpoints expose these data and how they are named.

**Comment by jvcsw** [comment]
I tried it two times with no response.
