### ISSUE TITLE
Expose Hourly, Daily and Monthly Plant data

### ISSUE THREAD

**Issue by tijsverkoyen** [tijsverkoyen/HomeAssistant-FusionSolar#96]
See https://support.huawei.com/enterprise/en/doc/EDOC1100261860/cf4fb068/plant-data-interfaces#EN-US_TOPIC_0000001174907346

## Real-Time Plant Data Interface
Is already used / implemented. But should be checked if all data is exposed.

## Hourly Plant Data Interface
Needs to be implemented. Question is if we should expose all hours, the sum, or only the latest hour?
There is no way in Home Assistant to expose an array of data. 

## Daily Plant Data Interface
Needs to be implemented. Question is if we should expose all hours, the sum, or only the latest hour?
There is no way in Home Assistant to expose an array of data. 

Is there a real benefit, as the total production is already available. And the new values will probably differ and confuse people.

## Monthly Plant Data Interface
Needs to be implemented. Question is if we should expose all hours, the sum, or only the latest hour?
There is no way in Home Assistant to expose an array of data. 

Is there a real benefit, as the total production is already available. And the new values will probably differ and confuse people.

## Yearly Plant Data Interface
Is already implemented with https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/95

**Comment by jvcsw** [comment]
In my case, hourly is not necessary. Weekly yes, but I think it doesn't exist.

Missing in the description "Lifetime Plant Data Interface", is implemented too like "Yearly Plant Data Interface".

**Comment by tijsverkoyen** [comment]
As I'm lacking the time I will not implement this at this point.
