### ISSUE TITLE
How do i know if my installer activated the API correctly

### ISSUE THREAD

**Issue by procoder1964** [tijsverkoyen/HomeAssistant-FusionSolar#97]
I have installed the integration in my Home assistant. The inverter and the dongle give values, but the battery and the meter give "onbekend" values.
Is this something what went wrong in the "activating" Northbound API by my installer, or is there something wrong on my side ?

**Comment by tijsverkoyen** [comment]
This probably means you don't have access to all data.
See https://github.com/tijsverkoyen/HomeAssistant-FusionSolar#northbound-api--openapi

**Comment by tijsverkoyen** [comment]
If you mail me your credentials I can test/debug this for you. You can mail me at `fusionsolar [at] verkoyen [dot] eu`

**Comment by procoder1964** [comment]
Sorry i dsaw now the closed issues.
I contacted my installer and i am waiting for feedback.
I must say you did a wonderful job to create this integration.

**Comment by procoder1964** [comment]
thanx for the help, but the problem was with the installer
